mono/xwt

Xwt.Gtk/Xwt.Gtk.csproj
Xwt.Gtk/Xwt.Gtk3.csproj
Xwt.Mac/Xwt.Mac.csproj
Xwt.WPF/Xwt.WPF.csproj
Xwt.XamMac/Xwt.XamMac.csproj
Xwt/Xwt.csproj

This PR simply enables Pdb generation in Release mode (for GitLink, see https://github.com/oxyplot/oxyplot/pull/284#issuecomment-66589745).

Enable Pdb creation in Release configuration

---

TestApps/Samples/Samples/ListView1.cs
Xwt.Gtk/Xwt.GtkBackend/Gtk2Extensions.cs
Xwt.Gtk/Xwt.GtkBackend/Gtk3Extensions.cs
Xwt.Gtk/Xwt.GtkBackend/TableViewBackend.cs

This PR solves the issue #411 in a more clean way.

[GTK] fix treeview background setting

---

Xwt.WPF/Xwt.WPFBackend/WindowFrameBackend.cs

This property has not yet been implemented in WPF.

[WPF] Window.Fullscreen getter and setter

---

TestApps/Samples/Samples/SliderSample.cs
Xwt.Gtk/Xwt.GtkBackend/Gtk2Extensions.cs
Xwt.Gtk/Xwt.GtkBackend/Gtk3Extensions.cs
Xwt.Gtk/Xwt.GtkBackend/SliderBackend.cs
Xwt.Mac/Xwt.Mac/SliderBackend.cs
Xwt.WPF/Xwt.WPFBackend/SliderBackend.cs
Xwt/Xwt.Backends/ISliderBackend.cs
Xwt/Xwt/Slider.cs

This PR adds a Stepping and Tick feature to the Slider widget.
* add step size
* add tick/step snapping
* make it possible to get the actual slider position relative to the widget bounds
* includes Gtk, Wpf, Mac support
PS: Gtk3 needs #424 for vertical sliders to function properly. Gtk2 without actual tick support (snapping works)

Add Slider stepping, ticks and position support

---

Xwt.Mac/Xwt.Mac/LabelBackend.cs
Xwt.Mac/Xwt.Mac/ListViewBackend.cs
Xwt.Mac/Xwt.Mac/Util.cs

This PR includes some small fixes in the Mac backend. See the commit messages for details.
This should also fix the stretching problem described in the forum: https://groups.google.com/d/topic/xwt-list/b22UvahrA00/discussion

[Mac] various small fixes

---

Testing/Tests/WindowTests.cs

[Test] Added tests for window initial location and size

---

Xwt.Gtk/Xwt.GtkBackend/PanedBackend.cs

I have cherry-picked relevant parts from #186 (f85e2ad601bfafe7da3c55be6b419ff31b1f4ad8 and 357714ef4b757b358daaa1e34f89b0562c8f92e8) and replaced the WidgetEvent subscription with a GLib notification to reduce event overhead.

[Gtk] paned events implementation

---

Xwt.WPF/Xwt.WPFBackend/WPFEngine.cs

Simply adds Wpf widget to image rendering support.

[Wpf] Add WPFEngine.RenderWidget

---

Xwt.Gtk/Xwt.GtkBackend/Conversion.cs
Xwt.Gtk/Xwt.GtkBackend/ListStoreBackend.cs
Xwt.Gtk/Xwt.GtkBackend/TableStoreBackend.cs
Xwt.Gtk/Xwt.GtkBackend/TableViewBackend.cs
Xwt.Gtk/Xwt.GtkBackend/TreeStoreBackend.cs
Xwt.Gtk/Xwt.GtkBackend/Util.cs

This PR includes a ITreeDataSource events implementation for TreeStoreBackend and some code cleanup.

Gtk tree ITreeDataSource events, cleanup and various fixes

---

Xwt.WPF/Xwt.WPFBackend.Utilities/CellUtil.cs

This PR is based on #483 and includes:
* CellView.Visible / CellView.VisibleField support
* TextCellView.Text support (if no TextField set)
* CellUtil.cs code cleanup 
(closes #483)

[Wpf] Enhance CellView FramworkElement generation (add Visibility, cleanup)

---

Xwt/Xwt.Backends/ApplicationContext.cs
Xwt/Xwt.Backends/BackendHost.cs
Xwt/Xwt.Backends/EventHost.cs
Xwt/Xwt.Backends/IBackend.cs
Xwt/Xwt.Backends/IWidgetBackend.cs
Xwt/Xwt.Backends/ToolkitEngineBackend.cs
Xwt/Xwt.Backends/TransferDataStore.cs
Xwt/Xwt/Application.cs
Xwt/Xwt/ButtonEventArgs.cs
Xwt/Xwt/DragEventArgs.cs
Xwt/Xwt/DragOperation.cs
Xwt/Xwt/IWidgetSurface.cs
Xwt/Xwt/KeyEventArgs.cs
Xwt/Xwt/MouseMovedEventArgs.cs
Xwt/Xwt/MouseScrolledEventArgs.cs
Xwt/Xwt/Toolkit.cs
Xwt/Xwt/TransferDataSource.cs
Xwt/Xwt/Widget.cs
Xwt/Xwt/WidgetAlignment.cs
Xwt/Xwt/WidgetSpacing.cs
Xwt/Xwt/XwtComponent.cs
Xwt/Xwt/XwtObject.cs

I've started to add more documentation for the API some weeks ago and pushed it now to the new [documentation](https://github.com/mono/xwt/tree/documentation) branch. It's far from being complete, but a good starting point.
I hope that someone can find some time to review this, so we can have a complete documentation for the 0.2 release. I'll push more docs during next days.

Add more Documentation

---

Xwt.Mac/NSStringAttributeKey.cs
Xwt.Mac/Xwt.Mac.csproj

Fixed for build break for Xwt.Mac (#514).

Fixed MonoMac compile break

---

Xwt.WPF/Xwt.WPFBackend/FontBackendHandler.cs

This is a finished implementation of #537:
* Always lookup custom fonts
* registered font collection should be static
* Revert AddFontResouceEx removal

[Wpf] Finish RegisterFontFromFile fix

---

Xwt.WPF/Xwt.WPFBackend/FontBackendHandler.cs

Added code to properly handle custom fonts for the WPF backend (issue #536).

Fixed WPF custom fonts

---

Xwt.Gtk/Xwt.GtkBackend/RichTextViewBackend.cs
Xwt.WPF/Xwt.WPFBackend/RichTextViewBackend.cs
Xwt.XamMac/Xwt.Mac/RichTextViewBackend.cs
Xwt/Xwt.Backends/IRichTextViewBackend.cs
Xwt/Xwt/RichTextView.cs

* Added `PlainText` property
* Added `ReadOnly` property

Editable Richtext

---

Xwt.WPF/Xwt.WPFBackend/RichTextViewBackend.cs

Fixed NRW on `RitchTextView.PlainText` property. (WPF)

[Xwt.WPF] Fixed NRW on `RitchTextView.PlainText` property. (WPF)

---

Xwt/Xwt.Backends/FontBackendHandler.cs

I added a few more fonts so we have better appearance on the platforms we support.

FontBackend: Better platform-specific fonts (Windows, Linux and OS X)

---

Xwt.Gtk/Xwt.GtkBackend/AlertDialogBackend.cs
Xwt.Gtk/Xwt.GtkBackend/DialogBackend.cs
Xwt.Gtk/Xwt.GtkBackend/GtkEngine.cs
Xwt.Gtk/Xwt.GtkBackend/GtkMacInterop.cs
Xwt.Gtk/Xwt.GtkBackend/GtkWorkarounds.cs
Xwt.Gtk/Xwt.GtkBackend/WindowFrameBackend.cs
Xwt.WPF/Xwt.WPFBackend/AlertDialogBackend.cs
Xwt.WPF/Xwt.WPFBackend/DialogBackend.cs
Xwt.WPF/Xwt.WPFBackend/WPFEngine.cs
Xwt.WPF/Xwt.WPFBackend/WindowFrameBackend.cs
Xwt.XamMac/Xwt.Mac/AlertDialogBackend.cs
Xwt.XamMac/Xwt.Mac/MacEngine.cs
Xwt.XamMac/Xwt.Mac/WindowBackend.cs
Xwt/Xwt.Backends/IWindowFrameBackend.cs
Xwt/Xwt.Backends/ToolkitEngineBackend.cs
Xwt/Xwt/Dialog.cs
Xwt/Xwt/MessageDialog.cs
Xwt/Xwt/Toolkit.cs

This PR adds NativeToolkit support and allows cross toolkit transient dialogs.

Add NativeToolkit support

---

Xwt.Gtk/Xwt.GtkBackend/ImageHandler.cs
Xwt.WPF/Xwt.WPFBackend/ImageHandler.cs
Xwt.XamMac/Xwt.Mac/ImageHandler.cs
Xwt/Xwt.Backends/ImageBackendHandler.cs
Xwt/Xwt.Drawing/Context.cs
Xwt/Xwt.Drawing/Image.cs
Xwt/Xwt.Drawing/StyleSet.cs

This PR enables `ToBitmap` conversion for custom drawn images with style support.
TODO: fix rendering to a Stream (`Image.Save()`)
**NOTE:** please do not merge! Needs more testing!

Fix ToBitmap support for custom drawn images

---

Xwt/Xwt.Drawing/HslColor.cs

Allocating arrays is not needed.

[Xwt] Optimized hsl color conversion.

---

Xwt.WPF/Xwt.WPFBackend/WpfDesktopBackend.cs

May be a little bit more robust than using reference comparison.

Improved detection of primary screen by using the appropriate property.

---

TestApps/Samples/Samples/ClipboardSample.cs
Xwt.Gtk/Xwt.GtkBackend/Util.cs
Xwt.WPF/Xwt.WPFBackend/ClipboardBackend.cs
Xwt.XamMac/Xwt.Mac/MacClipboardBackend.cs

When adding/getting Images to/from clipboard, they should be converted to their native representations and vice versa.

Fix image clipboard conversion

---

Xwt.Gtk/Xwt.GtkBackend/GtkInterop.cs
Xwt.Gtk/Xwt.GtkBackend/LabelBackend.cs
Xwt.Gtk/Xwt.GtkBackend/RichTextViewBackend.cs

This PR includes various fixes and optimizations for the Gtk RichTextViewBackend. See the commit messages for details.

[Gtk] RichTextView Fixes/Optimization

---

Xwt.Gtk/Xwt.GtkBackend/WindowFrameBackend.cs
Xwt.WPF/Xwt.WPFBackend/WindowFrameBackend.cs
Xwt.XamMac/Xwt.Mac/WindowBackend.cs
Xwt/Xwt.Backends/IWindowFrameBackend.cs
Xwt/Xwt/WindowFrame.cs

Implemented on all backends. Also some code of Mac backend that seemed to be a
leftover was removed.

Add HasFocus property to Window.

---

Xwt.Gtk.Mac/Xwt.Gtk.Mac.csproj
Xwt.XamMac/Xwt.XamMac.csproj

All other assemblies are signed already

Sign Mac backend assemblies

---

Xwt.Gtk/Xwt.Gtk3.csproj
Xwt.Gtk/Xwt.GtkBackend/DatePickerBackend.cs
Xwt.Gtk/Xwt.GtkBackend/FrameBackend.cs
Xwt.Gtk/Xwt.GtkBackend/WidgetBackend.cs
Xwt.WPF/Xwt.WPFBackend/ImageHandler.cs
Xwt.WPF/Xwt.WPFBackend/TextLayoutBackendHandler.cs
Xwt.XamMac/Xwt.Mac/DialogBackend.cs
Xwt.XamMac/Xwt.Mac/ExpanderBackend.cs
Xwt.XamMac/Xwt.Mac/ListViewBackend.cs
Xwt.XamMac/Xwt.Mac/ScrollbarBackend.cs
Xwt.XamMac/Xwt.Mac/TextEntryBackend.cs
Xwt.XamMac/Xwt.Mac/ViewBackend.cs
Xwt/Xwt.Backends/DesktopBackend.cs
Xwt/Xwt.Drawing/Image.cs
Xwt/Xwt/Calendar.cs
Xwt/Xwt/Frame.cs

This PR fixes almost all warnings and removes some deprecated/orphaned code.

Fix build warnings, remove orphaned code

---

Xwt.Gtk/Xwt.GtkBackend/WindowFrameBackend.cs
Xwt/Xwt/WindowFrame.cs

Fix some issues with initial window size.

Fix initial window bounds

---

Xwt.Gtk/Xwt.GtkBackend/ImageHandler.cs
Xwt.WPF/Xwt.WPFBackend/ImageHandler.cs
Xwt.XamMac/Xwt.Mac/ImageHandler.cs
Xwt/Xwt.Backends/ImageBackendHandler.cs
Xwt/Xwt.Drawing/Image.cs

We want the image size without loading and parsing the entire image

[Xwt] Add a faster way of getting the image size

---

Xwt.Gtk/Xwt.GtkBackend/GtkEngine.cs
Xwt.WPF/Xwt.WPFBackend/WPFEngine.cs
Xwt.XamMac/Xwt.Mac/MacEngine.cs
Xwt/Xwt.Backends/ToolkitEngineBackend.cs
Xwt/Xwt/Desktop.cs
Xwt/Xwt/Toolkit.cs

Cross-Toolkit Desktop Bounds support

---

Xwt.Gtk/Xwt.GtkBackend.CellViews/CustomCellRendererText.cs
Xwt.WPF/Xwt.WPFBackend.CellViews/TextCellViewBackend.cs
Xwt.WPF/Xwt.WPFBackend/TextEntryBackend.cs
Xwt/Xwt.csproj
Xwt/Xwt/TextCellView.cs
Xwt/Xwt/TextChangedEventArgs.cs

I have not tested the WPF backend, but pretty sure the Gtk backend is right.
This adds support for checking whether or not to modify a text cell's text based on the text being set.

[Xwt,Gtk,WPF] Add support for NewText handling in TextCellView

---

Xwt.Gtk/Xwt.GtkBackend/TextLayoutBackendHandler.cs

[Gtk] Fix TextLayout attributes reset when setting new text

---

Xwt/Xwt/Widget.cs

[Xwt] Make this error message more informative

---

Xwt.XamMac/Xwt.Mac/MacEngine.cs

Adds an event to the AppDelegate to return custom dock menu items

[Xwt.XamMac] Add application dock menu support to AppDelegate

---

Xwt.WPF/Xwt.WPFBackend/ExTreeView.cs

Reverts mono/xwt#722
This is causing a null reference inside WPF. This is probably because we are calling UpdateLayout at a time where it is incorrect to do so. Full stacktrace:
```
PresentationFramework.dll!System.Windows.Controls.VirtualizingStackPanel.ArrangeOverride(System.Windows.Size arrangeSize)	Unknown	Non-user code. Skipped loading symbols.
PresentationFramework.dll!System.Windows.FrameworkElement.ArrangeCore(System.Windows.Rect finalRect)	Unknown	Non-user code. Skipped loading symbols.
PresentationCore.dll!System.Windows.UIElement.Arrange(System.Windows.Rect finalRect)	Unknown	Non-user code. Skipped loading symbols.
PresentationFramework.dll!MS.Internal.Helper.ArrangeElementWithSingleChild(System.Windows.UIElement element, System.Windows.Size arrangeSize)	Unknown	Non-user code. …
```

Revert "ExTreeView: Fixed missing first root element"

---

Testing/CoreTests/ContextSwitchTests.cs
Testing/CoreTests/CoreTests.csproj
Testing/CoreTests/FakeToolkit.cs
Xwt.sln
Xwt/Xwt/Application.cs
Xwt/Xwt/Toolkit.cs

Make sure that the original sync context is restored after invoking on
a specific toolkit. Also added some unit tests.

Fix some context switching issues

---

TestApps/Samples/Samples/TreeViews.cs

This helps testing changes like https://github.com/mono/xwt/pull/739

Add TreeView multi-selection toggle to samples

---

Xwt.Gtk/Xwt.GtkBackend/TableViewBackend.cs
Xwt.WPF/Xwt.WPFBackend/ExTreeViewItem.cs

https://bugzilla.xamarin.com/show_bug.cgi?id=60266

TreeView: Let user drag multiple selected items

---

Xwt.Gtk/Xwt.GtkBackend/WidgetBackend.cs
Xwt.WPF/Xwt.WPFBackend/WidgetBackend.cs
Xwt.XamMac/Xwt.Mac/ViewBackend.cs
Xwt/Xwt/CursorType.cs

Add more cursor types
Fixes https://github.com/mono/xwt/issues/757

More cursor types

---

TestApps/XamMacTest/Main.cs
TestApps/XamMacTest/XamMacTest.csproj

This fixes XamMacTest build issues and arch detection.

[Mac] Update XamMacTest project configuration

---

Xwt/Xwt/Rectangle.cs

I need this to have Rectangle more similar to the WPFs Rect so I don't have to modify code that I'm porting and make helper methods...

Add helper properties and new constructor to Xwt.Rectangle

---

Xwt.Gtk/Xwt.GtkBackend/TableViewBackend.cs

[Gtk] Fix editable cells

---

Xwt.XamMac/Xwt.Mac.CellViews/CanvasTableCell.cs

[Mac] Fix CanvasTableCell flipping

---

TestApps/Samples/Samples/TreeViewEvents.cs

Fix build with mono 4.8

---

Xwt.XamMac/Xwt.Mac.CellViews/CellUtil.cs
Xwt.XamMac/Xwt.Mac.CellViews/ICellSource.cs
Xwt.XamMac/Xwt.Mac/TableViewBackend.cs

Frontend.AttackBackend requires a reference to the parent TableWidget

[Mac] Fix CellView.ParentWidget

---

TestApps/Samples/Samples/TreeViewEvents.cs
Xwt.XamMac/Xwt.Mac/IViewObject.cs
Xwt.XamMac/Xwt.Mac/ListViewBackend.cs
Xwt.XamMac/Xwt.Mac/NSTableViewBackend.cs
Xwt.XamMac/Xwt.Mac/OutlineViewBackend.cs
Xwt.XamMac/Xwt.Mac/TreeViewBackend.cs
Xwt.XamMac/Xwt.Mac/WidgetView.cs

This Patch improves (XamMac) TableViewBackend event handling:
* Unified event handling
* Allow setting events as handled
* Unified button conversion

[Mac] Unified event handling Pt.1

---

Xwt.WPF/Xwt.WPFBackend/TreeView.xaml

This should not change the appearance or behavior, but should make it
easier to override these styles externally.

[WPF] Move ExTreeViewItem brush styles from template to outer style

---

Xwt.XamMac/Xwt.Mac/ContextBackendHandler.cs
Xwt.XamMac/Xwt.Mac/TextLayoutBackendHandler.cs

TextLayoutBackendHandler completely rewritten using NSLayoutManager :)
* supports now all attributes
* correct background color rendering/alignment
* fixed size calculation
* full TextLayout API support

[Mac] NSLayoutManager based TextLayoutBackend

---

Xwt.XamMac/Xwt.Mac/TextLayoutBackendHandler.cs

Temporary adding the foreground color attribute will
override all other foreground color changes. In order to
apply a default foreground color from the current context,
it needs to be applied first.

[Mac] Fix default TextLayout foreground color

---

Xwt.WPF/Xwt.WPFBackend/TextEntryBackend.cs

Issue pointed out by @alexandrvslv in #815
Fixes #815

[WPF] Fix ReadOnly property on TextEntryBackend

---

Xwt.WPF/Xwt.WPF.csproj
Xwt.WPF/Xwt.WPFBackend/AccessibleBackend.cs
Xwt.WPF/Xwt.WPFBackend/WPFEngine.cs

Ultra basic backend for a few key a11y properties.

[WPF] Basic accessibility backend

---

Xwt/Xwt.Backends/BackendHost.cs
Xwt/Xwt/Paned.cs
Xwt/Xwt/Toolkit.cs
Xwt/Xwt/WindowFrame.cs
Xwt/Xwt/XwtComponent.cs

Doesn't fix NativeWindowFrame and (possible?) CellView leaks

Leak fix attempt

---

Xwt.WPF/Xwt.WPFBackend/MenuBackend.cs

The Designer code uses this to theme the WPF menu.

Added an accessor method to get the native ContextMenu

---

Xwt/Xwt.Backends/BackendHost.cs
Xwt/Xwt/Paned.cs
Xwt/Xwt/Toolkit.cs
Xwt/Xwt/WindowFrame.cs
Xwt/Xwt/XwtComponent.cs

Reverts mono/xwt#760
It is causing a regression in VSMac: https://github.com/mono/monodevelop/issues/4972

Revert "Leak fix attempt"

---

Xwt.Gtk/Xwt.GtkBackend/CheckBoxBackend.cs
Xwt.WPF/Xwt.WPFBackend/CheckBoxBackend.cs
Xwt.XamMac/Xwt.Mac/CheckBoxBackend.cs
Xwt/Xwt.Backends/ICheckBoxBackend.cs
Xwt/Xwt/CheckBox.cs

Mirrors the option available for buttons.

Add mnemonic option to checkboxes

---

Xwt.Gtk/Xwt.Gtk3.dll.config

`/usr/local/lib/libgdk-3.0.dylib: Mach-O 64-bit dynamically linked shared library x86_64`

Fix Mac dllmap for Gtk3

---

TestApps/Samples/Samples/FileSelectorSample.cs
Xwt/Xwt.Backends/IFileSelectorBackend.cs
Xwt/Xwt/FileSelector.cs

The FileSelect now pass the Filters to the backend FileDialogSelector

Fix file selector filters

---

Xwt.XamMac/Xwt.Mac/MacEngine.cs
Xwt.XamMac/Xwt.Mac/SearchTextEntryBackend.cs
Xwt.XamMac/Xwt.Mac/TextEntryBackend.cs
Xwt.XamMac/Xwt.XamMac.csproj

Adds the missing SearchTextEntryBackend to Xwt.XamMac:

[Mac] Add SearchTextEntryBackend

---

Xwt.WPF/Xwt.WPFBackend/DataConverter.cs
Xwt.WPF/Xwt.WPFBackend/RichTextViewBackend.cs
Xwt.WPF/Xwt.WPFBackend/WidgetBackend.cs

Makes it possible to scroll ScrollView via keyboard on Windows via introducing a Backend flag `ForwardsKeyPressesToParent`.

[WPF] Scrollview keyboard a11y

---

Xwt/Xwt/Key.cs

Adds some missing key constants

[Xwt] Add some missing Key constants

---

Xwt.WPF/Xwt.WPFBackend/ButtonBackend.cs

* This will fix an issue using Buttons and menuButtons with WPF backend were being layout incorrectly.

[WPF] Added penel to button chrome factory.

---

Xwt.Gtk/Xwt.GtkBackend/AccessibleBackend.cs
Xwt.WPF/Xwt.WPFBackend/AccessibleBackend.cs
Xwt.WPF/Xwt.WPFBackend/ExListView.cs
Xwt.WPF/Xwt.WPFBackend/ExTreeView.cs
Xwt.WPF/Xwt.WPFBackend/ExTreeViewItem.cs
Xwt.XamMac/Xwt.Mac/AccessibleBackend.cs
Xwt/Xwt.Accessibility/Accessible.cs
Xwt/Xwt.Accessibility/IAccessibleBackend.cs

[a11y][WPF] AutomationPeer customization support for TreeView and ListView

---

Xwt/Xwt.Backends/BackendHost.cs
Xwt/Xwt/Paned.cs
Xwt/Xwt/Toolkit.cs
Xwt/Xwt/WindowFrame.cs
Xwt/Xwt/XwtComponent.cs

Revert "Fix leaks coming in from event subscription"

---

TestApps/XamMacTest/Info.plist
Xwt.XamMac/Xwt.Mac/WindowBackend.cs

[Mac] Use INSWindowDelegate instead of NSWindow events

---

Xwt.XamMac/Xwt.Mac/WindowBackend.cs

Optimize ObserveValue implementation

---

TestApps/XamMacTest/Info.plist
Xwt.XamMac/Xwt.Mac/WindowBackend.cs

Fixes VSTS #935131
Backport of #945

[d16-2][Mac] Use INSWindowDelegate instead of NSWindow events

---

Xwt.XamMac/Xwt.Mac/ExpanderBackend.cs

The Xwt.XamMac expander is totally broken. Because of the broken size calculation it's not even shown in the Samples app and with a fixed size request it looks really odd:
This PR includes:
* Fix PreferredSize and final size calculation
* Use selectors instead of events / fix some leaks
* Improve expander label pointer behaviour
* Remove custom gradient background
And looks like this now:

[Mac] Rewrite Expander backend implementation

---

Xwt/Xwt/FileDialog.cs
Xwt/Xwt/FileSelector.cs

This fixes #817 and supersedes #905

Fix FileSelector and FileDialog results after cancellation

---

TestApps/Samples/Samples/ButtonSample.cs
Xwt.Gtk/Xwt.GtkBackend/ButtonBackend.cs
Xwt.Gtk/Xwt.GtkBackend/LabelBackend.cs
Xwt.Gtk/Xwt.GtkBackend/MenuBackend.cs
Xwt.Gtk/Xwt.GtkBackend/MenuItemBackend.cs
Xwt.Gtk/Xwt.GtkBackend/Util.cs
Xwt.WPF/Xwt.WPFBackend/ButtonBackend.cs
Xwt.WPF/Xwt.WPFBackend/LabelBackend.cs
Xwt.WPF/Xwt.WPFBackend/MenuItemBackend.cs
Xwt.WPF/Xwt.WPFBackend/Util.cs
Xwt.XamMac/Xwt.Mac/ButtonBackend.cs
Xwt.XamMac/Xwt.Mac/MenuItemBackend.cs
Xwt/Xwt.Backends/IButtonBackend.cs
Xwt/Xwt.Backends/IMenuItemBackend.cs
Xwt/Xwt/Button.cs
Xwt/Xwt/FormattedText.cs
Xwt/Xwt/Menu.cs
Xwt/Xwt/MenuItem.cs

Adding MenuButton support for formatted text to be used in MenuItems and the selected item. 
Backends:

[WPF][XamMac][GtkMac] Enable formatted text in Buttons

---

Testing/Info.plist
Testing/MacTestRunner.csproj
Testing/MacTestRunner/Main.cs

[Mac][Tests] Change the MacTestRunner project type to XamMac

---

Xwt.WPF/Xwt.WPF.csproj
Xwt/Xwt.csproj

Remove the NoBuild as proposed in https://github.com/dotnet/sdk/issues/3001

Fix build with .NET Core 3.0

---

Xwt.Gtk/Xwt.GtkBackend/FontBackendHandler.cs
Xwt.Gtk/Xwt.GtkBackend/SelectFontDialogBackend.cs
Xwt.WPF/Xwt.WPFBackend/DataConverter.cs
Xwt.XamMac/Xwt.Mac/FontBackendHandler.cs
Xwt.XamMac/Xwt.Mac/SelectFontDialogBackend.cs
Xwt.XamMac/Xwt.Mac/Util.cs
Xwt/Xwt.Backends/ISelectFontDialogBackend.cs
Xwt/Xwt.Drawing/Font.cs
Xwt/Xwt/SelectFontDialog.cs

See:
https://github.com/mono/monodevelop/pull/8106

Added support for mac font weights that range from 0-15.

---

Xwt.XamMac/Xwt.Mac/ImageHandler.cs

[Mac] Fix NRE in CustomImage

---

Xwt.XamMac/Xwt.Mac/FileDialogBackend.cs
Xwt.XamMac/Xwt.Mac/OpenFileDialogBackend.cs
Xwt.XamMac/Xwt.Mac/SaveFileDialogBackend.cs
Xwt.XamMac/Xwt.Mac/SelectFolderDialogBackend.cs

See for details: https://github.com/xamarin/xamarin-macios/issues/6474
Fixes VSTS #989519

[Mac] Use static NSSavePanel to avoid crashes on Catalina

---

Xwt.XamMac/Xwt.Mac/FileDialogBackend.cs
Xwt.XamMac/Xwt.Mac/OpenFileDialogBackend.cs
Xwt.XamMac/Xwt.Mac/SaveFileDialogBackend.cs
Xwt.XamMac/Xwt.Mac/SelectFolderDialogBackend.cs

See for details: https://github.com/xamarin/xamarin-macios/issues/6474
Backport of #982
(cherry picked from commit 4095069e65306f5b9e4a4a21175fcfa2918a8889)

[d16-3][Mac] Use static NSSavePanel to avoid crashes on Catalina

---

Xwt/Xwt/FileSelector.cs
Xwt/Xwt/FolderSelector.cs

Changes based on reviews in https://github.com/xamarin/vsmac-xamarin-extensions/pull/403
backport of : https://github.com/mono/xwt/pull/995

[d16-4]Update FileSelector and FolderSelector accessibility labels

---

Xwt/Xwt/FileSelector.cs
Xwt/Xwt/FolderSelector.cs

This reverts https://github.com/mono/xwt/pull/995

Revert changes to file and folder selector

---

Xwt.XamMac/Xwt.Mac.CellViews/ImageTableCell.cs

[Mac] Add sel style support to ImageTableCell

---

TestApps/Samples/Samples/ComboBoxes.cs
Xwt.Gtk/Xwt.GtkBackend/ComboBoxEntryBackend.cs
Xwt.WPF/Xwt.WPFBackend/ComboBoxEntryBackend.cs
Xwt.XamMac/Xwt.Mac/ComboBoxEntryBackend.cs
Xwt/Xwt.Backends/IComboBoxEntryBackend.cs
Xwt/Xwt/ComboBoxEntry.cs

[16.4] Add ComboBoxEntry Completion support

---

Xwt/Xwt.Accessibility/Accessible.cs
Xwt/Xwt/FileSelector.cs
Xwt/Xwt/FolderSelector.cs
Xwt/Xwt/Widget.cs

This allows custom widgets to handle Accessible changes and fixes FileSelector/FolderSelector accessibility.

Fix issues with custom widget accessibility

---

Xwt/Xwt.Accessibility/Accessible.cs
Xwt/Xwt/FileSelector.cs
Xwt/Xwt/FolderSelector.cs
Xwt/Xwt/Widget.cs

This allows custom widgets to handle Accessible changes and fixes FileSelector/FolderSelector accessibility.
Backport of #1025

[16.5] Fix issues with custom widget accessibility

---

Xwt/Xwt.Accessibility/Accessible.cs
Xwt/Xwt/FileSelector.cs
Xwt/Xwt/FolderSelector.cs
Xwt/Xwt/Widget.cs

This allows custom widgets to handle Accessible changes and fixes FileSelector/FolderSelector accessibility.
Backport of #1025

[16.4] Fix issues with custom widget accessibility

---

Xwt.XamMac/Xwt.Mac/KeyboardUtil.cs
Xwt/Xwt/KeyEventArgs.cs

NSKeyEvent contains some data related to the characters pressed, so store that in KeyEventArgs

[Xwt] Store the characters data from NSEvent in KeyEventArgs

---

Xwt.XamMac/Xwt.Mac/MacSystemInformation.cs
Xwt.XamMac/Xwt.Mac/NSTableViewBackend.cs
Xwt.XamMac/Xwt.Mac/OutlineViewBackend.cs
Xwt.XamMac/Xwt.Mac/TableViewBackend.cs

Big Sur introduced a new NSTableViewStyle and additional weird behavior
breaking the layout and CanvasCell rendering.

[Mac] Fix TableView layout and rendering on BigSur

---

Xwt.XamMac/Xwt.Mac/PanedBackend.cs

Fix setting the split view divider position, delaying setting it until it's shown.
This is needed to fix https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1407194.

Support setting splitter position

---

Xwt.XamMac/Xwt.Mac.CellViews/CanvasTableCell.cs
Xwt.XamMac/Xwt.Mac/BoxBackend.cs
Xwt.XamMac/Xwt.Mac/CanvasBackend.cs
Xwt.XamMac/Xwt.Mac/ContextBackendHandler.cs
Xwt.XamMac/Xwt.Mac/DialogBackend.cs
Xwt.XamMac/Xwt.Mac/FrameBackend.cs
Xwt.XamMac/Xwt.Mac/GradientBackendHandler.cs
Xwt.XamMac/Xwt.Mac/ListViewBackend.cs
Xwt.XamMac/Xwt.Mac/MacDesktopBackend.cs
Xwt.XamMac/Xwt.Mac/PanedBackend.cs
Xwt.XamMac/Xwt.Mac/PathBackendHandler.cs
Xwt.XamMac/Xwt.Mac/PopoverBackend.cs
Xwt.XamMac/Xwt.Mac/ScrollControlBackend.cs
Xwt.XamMac/Xwt.Mac/ScrollViewBackend.cs
Xwt.XamMac/Xwt.Mac/TextLayoutBackendHandler.cs
Xwt.XamMac/Xwt.Mac/TreeViewBackend.cs
Xwt.XamMac/Xwt.Mac/WindowFrameBackend.cs

Add using statements so we can build with older or newer Xamarin.Mac.
https://github.com/xamarin/xamarin-macios/blob/f0ff01f5686e925abb5d68b6dcb52c35579595c4/dotnet/BreakingChanges.md

Support nfloat/NMath moving from System to ObjCRuntime

---

Xwt.XamMac/Xwt.Mac/AlertDialogBackend.cs
Xwt.XamMac/Xwt.Mac/ContextBackendHandler.cs
Xwt.XamMac/Xwt.Mac/ListViewBackend.cs
Xwt.XamMac/Xwt.Mac/OutlineViewBackend.cs
Xwt.XamMac/Xwt.Mac/PopoverBackend.cs
Xwt.XamMac/Xwt.Mac/RichTextViewBackend.cs
Xwt.XamMac/Xwt.Mac/TextLayoutBackendHandler.cs
Xwt.XamMac/Xwt.Mac/TreeViewBackend.cs
Xwt.XamMac/Xwt.Mac/Util.cs
Xwt.XamMac/Xwt.Mac/ViewBackend.cs
Xwt.XamMac/Xwt.Mac/WindowBackend.cs
Xwt.XamMac/Xwt.XamMac.csproj

Preview 13 of the macos workload has several breaking changes, not all of them documented yet. This must be merged carefully.

Build: Use a 6.0.200 SDK and macos workload P13

---

Xwt.XamMac/Xwt.Mac/KeyboardUtil.cs

Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1477144

Add some more missing punctuation

---

Xwt.XamMac/Xwt.Mac/KeyboardUtil.cs
Xwt/Xwt/KeyEventArgs.cs

Parse the hardware key so we can use it for keyboard shortcuts.
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1418403

Add a hardware key field to get the physically pressed key

---

Xwt.XamMac/Xwt.Mac.CellViews/CompositeCell.cs
Xwt.XamMac/Xwt.Mac/AlertDialogBackend.cs
Xwt.XamMac/Xwt.Mac/ButtonBackend.cs
Xwt.XamMac/Xwt.Mac/DialogBackend.cs
Xwt.XamMac/Xwt.Mac/LabelBackend.cs
Xwt.XamMac/Xwt.Mac/MenuButtonBackend.cs
Xwt.XamMac/Xwt.Mac/RichTextViewBackend.cs
Xwt.XamMac/Xwt.Mac/SearchTextEntryBackend.cs
Xwt.XamMac/Xwt.Mac/TextEntryBackend.cs
Xwt.XamMac/Xwt.Mac/TreeViewBackend.cs
Xwt.XamMac/Xwt.Mac/WindowBackend.cs

Part of https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1493053

Mac: s/IntPtr/NativeHandle for several missed constructors

---

Xwt.XamMac/Xwt.Mac/KeyboardUtil.cs

Changing to key codes really broken international layouts

Revert changes to KeyCode handling

---

Xwt.XamMac/Xwt.Mac/FontBackendHandler.cs

Taken from https://github.com/xamarin/vsmac/pull/9164

Mac: Add extensions for converting from NSFont
