mono/xwt

- Xwt.Gtk/Xwt.GtkBackend/NotebookBackend.cs
When there are too many tabs to fit the Notebook, scroll arrows are added.
> [GTK] Notebook tabs scrollable

- Xwt/Xwt/Toolkit.cs
GTK3 is not loaded in Xwt. This pull request enables it.
> [GTK] Load GTK3 toolkit.

- Xwt.Gtk/Xwt.GtkBackend/WidgetBackend.cs
- Xwt.Gtk/Xwt.GtkBackend/WidgetBackendGtk2.cs
- Xwt.Gtk/Xwt.GtkBackend/WidgetBackendGtk3.cs
This PR fixes some Gtk3 sizing issues, especially for vertical widgets like Sliders with vertical orientation. Fixes additionally cases when widgets had a zero size initially or min sizes without effect.
* request widget size based on Gtk.SizeRequestMode
* always set Gtk size requests
> [Gtk3] fix sizing for different SizeRequestModes

- Xwt.Gtk/Xwt.GtkBackend/WidgetBackend.cs
This one adds virtual event args conversion methods (Gtk to Xwt) to the WigetBackend base class.
Many event arguments have private members, that can not be modified after creation. Virtual conversion methods make it possible to modify the arguments before they are passed to the frontend.
> [Gtk] add virtual event args conversion methods

- Xwt.WPF/Xwt.WPFBackend/RichTextViewBackend.cs
Markdown linebreaks add an empty Run element to the FlowDocument, which
adds a leading whitespace to the next line. This fixes that bug.
In the current implementations: `Line 1  \nLine2` leads to:
<FlowDocument
xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation">
<Paragraph>
<Run>Line 1</Run>
<LineBreak />
<Run />
<Run>Line 2</Run>
</Paragraph>
</FlowDocument>
and this renders to: 
This commit changes that to:
<FlowDocument
xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation">
<Paragraph>
<Run>Line 1</Run>
<LineBreak />
<Run>Line 2</Run>
</Paragraph>
</FlowDocument>
> [WPF] Removed empty Run elements in Markdown

- Xwt.Gtk/Xwt.CairoBackend/CairoContextBackendHandler.cs
- Xwt.Gtk/Xwt.GtkBackend.CellViews/Gtk2CellRendererCustom.cs
- Xwt.Gtk/Xwt.GtkBackend/CanvasBackend.cs
- Xwt.Gtk/Xwt.GtkBackend/CanvasBackendGtk2.cs
- Xwt.Gtk/Xwt.GtkBackend/CanvasBackendGtk3.cs
Gtk3 DrawingTransforms sample does not draw correctly with Gtk3 at present.  This is because the context origin has to be adjusted, so that the new Context.CTM is always the Identity Matrix.  In addition, the invalidated area supplied to the OnDraw routines needs adjusting for the same reason.
> [Gtk] context fix for Gtk2 and Gtk3

- Xwt.Gtk/Xwt.GtkBackend/Gtk2ViewPort.cs
- Xwt.Gtk/Xwt.GtkBackend/Gtk3ViewPort.cs
- Xwt.Gtk/Xwt.GtkBackend/ScrollViewBackend.cs
use a simple Box (like for Gtk2) and implementing IScrollableImplementor
instead of a Viewport (not allowing to override adjustment handling).
(fixes #468)
> [Gtk3] fix widgets with enabled SupportsCustomScrolling

- Xwt.Mac/Xwt.Mac/CustomWidgetBackend.cs
- Xwt.Mac/Xwt.Mac/MacEngine.cs
- Xwt.Mac/Xwt.Mac/ViewBackend.cs
CustomWidgetBackend should adjust the size of the child widget to match own bounds directly (without AutoMode). This fixes display and sizing issues for custom widgets with containers.
Includes #226
> [Mac] fix CustomWidgetBackend / XwtWidgetBackend sizing

- Xwt.WPF/Xwt.WPFBackend/CustomWidgetBackend.cs
- Xwt.WPF/Xwt.WPFBackend/WPFEngine.cs
* fix WPFEngine.HasNativeBackend for XwtWidgetBackend
* CustomWidgetBackend should rearrange its child on size changes.
Partial fix for ColorPicker (XwtBackendWidget)
> [Wpf] fix XwtWidgetBackend containers support

- Xwt.WPF/Xwt.WPFBackend/CanvasBackend.cs
OnDraw is triggered too early by Wpf when a canvas gets initialized.
Delay drawing until the widget and its parents are registered. Otherwise things like ImageBuilder throw Exceptions because the canvas has no parent window until it is fully initialized.
Partial fix for ColorPicker (XwtBackendWidget)
> [Wpf] fix Canvas drawing without ParentWindow

- Xwt.Gtk/Xwt.GtkBackend/GtkEngine.cs
Some Gtk Widgets use an additional Gdk.Window for drawing
and/or their bounds do not match their GdkWindow window. A workaround
is to check if the window and widget allocation sizes are equal.
In that case the widget allocation offset could be relative to a higher level
window and should be ignored.
> [Gtk] add RenderWidget coordinates check

- TestApps/Samples/Samples/ListView2.cs
- Xwt.Gtk/Xwt.GtkBackend/ListViewBackend.cs
- Xwt.Mac/Xwt.Mac.CellViews/CheckBoxTableCell.cs
- Xwt.Mac/Xwt.Mac.CellViews/CompositeCell.cs
- Xwt.Mac/Xwt.Mac.CellViews/ICellSource.cs
- Xwt.Mac/Xwt.Mac/ListViewBackend.cs
- Xwt.Mac/Xwt.Mac/TableViewBackend.cs
- Xwt.Mac/Xwt.Mac/TreeViewBackend.cs
- Xwt.WPF/Xwt.WPFBackend/ListViewBackend.cs
- Xwt/Xwt.Backends/IListViewBackend.cs
- Xwt/Xwt/ListView.cs
Adds ListView.CurrentEventRow (same as 9b06b9e for TreeView, but for ListView).
This allows event handlers to know which row was changed.
* includes Gtk and Mac implementations
* MAC: adds CurrentEventRow for TreeView, too
TODO: Wpf!
> Add CurrentEventRow to ListView

- Xwt.WPF/Xwt.WPFBackend/BoxBackend.cs
Initialize the background of the underlying Panel with a transparent background.
A Panel does not receive mouse events, if no background is set.
(see MSDN remarks: http://msdn.microsoft.com/en-us/library/system.windows.controls.panel(v=vs.110).aspx)
> [WPF] fix canvas mouse events

- TestApps/Samples/Samples/TreeViews.cs
- Xwt.Mac/Xwt.Mac.csproj
- Xwt.Mac/Xwt.Mac/OutlineViewBackend.cs
- Xwt.Mac/Xwt.Mac/TreeViewBackend.cs
I've accidentaly deleted my xwt branch, Iam creating this PR again (reference to pull request: 319)
Iam referencing my Issue #315 from thursday, I have to fix this issue, cause I need it ;) It's something like "example solution", Iam new in Mono / Mono Mac / c#, but it works... I try to find mouse handler for List / TreeView but I was no able to find it... I have to extend NSOutlineView, like "Hywel Thomas" does it in "WidgetView".
I'am sorry for this "PR-mess" :-1:
> [MAC] Extends NSOutlineView for proper handling mouse events

- Xwt.Gtk/Xwt.GtkBackend/WidgetBackend.cs
The cursor should be set only when inside the widget.
Set the cursor when mouse enters and reset it to parents
default (null in Gtk) when mouse leaves the widget.
(fix can be reproduced on the Cursors example with Gtk2)
> [Gtk] fix cursor handling

- Xwt.WPF/Xwt.WPFBackend/ExTreeView.cs
What this code does... It forces loading of vitalized TreeViewItem so SelectItem can be performed... Before exception was throw because treeViewItem was null and unit tests running crashed...
> [Wpf] Fixing unit tests crash + TreeView.HiddenTree test

- Xwt.Gtk/Xwt.GtkBackend/PopoverBackend.cs
The Gtk PopoverBackend can reuse the popover window and destroy it on Dispose, instead of creating a new window each time the Popover is shown.
> [GTK] fix resize artifacts, reuse popover window

- Xwt.WPF/Xwt.WPFBackend/ExTreeViewItem.cs
When one or more top nodes in TreeView are expanded, calling `Clear()` on the ITreeDataSource raises an exception.
This is due to `OnCollapsed (RoutedEventArgs e)` being called in ExTreeViewItem, and this cast fails:
var node = (TreeStoreNode)DataContext;
Specifically: `DataContext` is `DisconnectedItem` of type `MS.Internal.NamedObject`
> [WPF] Calling TreeStore.Clear() raises exception in ExTreeViewItem

- Xwt.Mac/Xwt.Mac/ButtonBackend.cs
- Xwt.Mac/Xwt.Mac/MenuButtonBackend.cs
- Xwt.Mac/Xwt.Mac/ToggleButtonBackend.cs
- Xwt.Mac/Xwt.Mac/Util.cs
*Update: fixes button colors*
**Button sizing:**
The default NSBezelStyle.Rounded style (which is the default for text buttons on Mac)  does not support cusom heights.
When a custom size or image is used, the style should be set to NSBezelStyle.RegularSquare (the default for image or custom buttons on Mac) for the sizing to work as expected.
> [Mac] fix button sizing and colors

- Xwt/Xwt/Command.cs
Even if implemented (e.g. IAlertDialogBackend) the command icons are never assigned, since private. This PR lets the user set custom command icons and labels.
This is connected to #53, where a new Command concept is proposed. Until we have some more sophisticated solution, this is an easy way to allow icons on dialog buttons, or create menu items using commands.
> Commands with writable properties

- Xwt.Gtk/Xwt.GtkBackend/Conversion.cs
- Xwt.Gtk/Xwt.GtkBackend/Gtk2Extensions.cs
- Xwt.Gtk/Xwt.GtkBackend/Gtk3Extensions.cs
- Xwt.Gtk/Xwt.GtkBackend/GtkAlertDialog.cs
- Xwt.Gtk/Xwt.GtkBackend/GtkWorkarounds.cs
Let Gtk.MessageDialog do the layout stuff and make use of Gtk.MessageType for a more native icon styles.
This change makes message dialogs look more native and closer to gtk design guidelines (especially with gtk3). Additionally the dialogs should be compatible with more themes (providing special designs for message dialogs).
(an extended message dialog sample has been added to the sample app, too: #380)
Some example screenshots (Ubuntu - Gnome 3):
Before (gtk2/3)| After (gtk2) | After (gtk3)
------------ | ------------- | --------------
> [Gtk] Optimize message dialogs

- Xwt.Mac/Xwt.Mac/AlertDialogBackend.cs
This PR adds the following fixes and missing features to the AlertDialogBackend on Mac:
* Fix exception thrown when no default button set
* Add Icon support
* Set dialog parent window if requested
* Add ApplyToAll implementation
* Add Message Options
> [Mac] add missing AlertDialogBackend features

- Xwt.Gtk/Xwt.GtkBackend/FontBackendHandler.cs
- Xwt.Mac/Xwt.Mac/FontBackendHandler.cs
- Xwt.WPF/Xwt.WPFBackend/DataConverter.cs
- Xwt.WPF/Xwt.WPFBackend/FontBackendHandler.cs
- Xwt/Xwt.Backends/FontBackendHandler.cs
- Xwt/Xwt.Drawing/Font.cs
While working on the FontSelector widget I've found some issues with the current font implementation. 
1. missing weight values (a84e9ff): according to [Pango API](https://developer.gnome.org/pango/stable/pango-Fonts.html#PangoWeight) there are some additional predefined weight values and they have backend specific (Wpf/Mac) pendants. So I have added them and optimized the backend mappings for better fitting.
2. little Mac issue (016c67a): the trait mask has to be updated, when changing the font weight (NSFontTraitMask.Bold, NSFontTraitMask.Unbold)
3. A new function to retrieve available font family variants (c3000f6): since the Font object allows to apply any weight, style and stretch combination (even invalid), I was missing a function to get really available/valid combinations …
> Font optimization

- Xwt.Gtk/Xwt.Gtk3.csproj
- Xwt.Gtk/Xwt.GtkBackend/ButtonBackend.cs
- Xwt.Gtk/Xwt.GtkBackend/CheckBoxBackend.cs
- Xwt.Gtk/Xwt.GtkBackend/ComboBoxBackend.cs
- Xwt.Gtk/Xwt.GtkBackend/PanedBackend.cs
- Xwt.Gtk/Xwt.GtkBackend/PanedBackendGtk3.cs
- Xwt.Gtk/Xwt.GtkBackend/RadioButtonBackend.cs
- Xwt.Gtk/Xwt.GtkBackend/WebViewBackend.cs
- Xwt.Gtk/Xwt.GtkBackend/WidgetBackend.cs
Some Gtk Widgets have their own Gdk.Window. Most of the events are not raised for such widgets, because WidgetBackend (and its derivates) automatically put them into an EventBox and subscribe its events, instead of using the widgets directly.
This PR allows Gtk backends to overide EventBox allocation and handle events directly for widgets which have a Gdk.Window already. This is achieved though the WidgetBackend.NeedsEventBox property, which is true by default (keeps original behavior). Backends can set it to false during their initialization and force the base class WidgetBackend to subscribe the events from the widgets directly.
I've tested almost all widgets (but not all events, only Mouse events) and added the override to widgets, that did not work previously. Maybe some other …
> [Gtk] fix evt handling for widgets with own window

- TestApps/Samples/Samples/ListView1.cs
- TestApps/Samples/Samples/TreeViews.cs
- Xwt.Mac/Xwt.Mac/ListViewBackend.cs
- Xwt.Mac/Xwt.Mac/TreeViewBackend.cs
- Xwt/Xwt/TreeStore.cs
This is the same as ##316, but reloads the views not only on row changes, but also on  deletion/insertion.
(closes #314, closes #316)
> [Mac] reload tree/list on data source changes

- Xwt.XamMac/Xwt.Mac/ListViewBackend.cs
- Xwt.XamMac/Xwt.Mac/TreeViewBackend.cs
The default behavior when selecting single rows should be extending the selection when SelectionMode is set to ```SelectionMode.Multiple``` (WPF and GTK work this way). The current Mac behavior is to replace the selection (deselect previously selected rows), which is fixed here.
> [MAC] Respect SelectionMode on row selection

- TestApps/Samples/Samples/ListBoxSample.cs
- TestApps/Samples/Samples/ListView1.cs
- TestApps/Samples/Samples/TreeViews.cs
- Xwt.Gtk/Xwt.GtkBackend/ListViewBackend.cs
- Xwt.Gtk/Xwt.GtkBackend/TreeViewBackend.cs
- Xwt.WPF/Xwt.WPF.csproj
- Xwt.WPF/Xwt.WPFBackend/ExListBox.cs
- Xwt.WPF/Xwt.WPFBackend/ExListBoxItem.cs
- Xwt.WPF/Xwt.WPFBackend/ExListView.cs
- Xwt.WPF/Xwt.WPFBackend/ExListViewItem.cs
- Xwt.WPF/Xwt.WPFBackend/ExTreeView.cs
- Xwt.WPF/Xwt.WPFBackend/ListBoxBackend.cs
- Xwt.WPF/Xwt.WPFBackend/ListViewBackend.cs
- Xwt.WPF/Xwt.WPFBackend/TreeViewBackend.cs
- Xwt.XamMac/Xwt.Mac/ListViewBackend.cs
- Xwt.XamMac/Xwt.Mac/TreeViewBackend.cs
- Xwt/Xwt.Backends/IListBoxBackend.cs
- Xwt/Xwt.Backends/IListViewBackend.cs
- Xwt/Xwt.Backends/ITreeViewBackend.cs
- Xwt/Xwt/ListBox.cs
- Xwt/Xwt/ListView.cs
- Xwt/Xwt/TreeView.cs
This adds a FocusedRow property to TreeView, ListView and ListBox to get/set the row with the keyboard focus.
There is a special case on Mac: there is not keyboard focus feature for single rows, but only row selection. So on Mac FocusedRow is always the first selected row (selects a row, when FocusedRow is assigned, or returns the first selected row).
(fixes #376)
> Add TreeView/ListView FocusedRow property

- TestApps/Samples/MainWindow.cs
- TestApps/Samples/Samples.csproj
- TestApps/Samples/Samples/WidgetFocus.cs
- Xwt.Gtk/Xwt.GtkBackend/WidgetBackend.cs
This is based on #310. As discussed ```Widget.IsFocus = true``` is not always enough. Some Gtk widgets (ListView, maybe others) need sometimes a GrabFocus() to receive keyboard focus and those which don't need it (should) behave as expected/before. Additionally an example is included.
Note: I've removed ```void SetFocus (Gtk.Widget w)``` which is never used.
> [Gtk] fix SetFocus

- Xwt/Xwt/ColorSelector.cs
This fixes the problem when the default ColorSelector is rendered without a parent window (e.g. when initialized with Wpf, or in a foreign host context). In this case the color box is drawn without taking the current screen scale factor into account.
> Fix default ColorSelectorBackend without window

- Xwt.Gtk/Xwt.GtkBackend/GtkWorkarounds.cs
- Xwt.Gtk/Xwt.GtkBackend/WidgetBackend.cs
**EDIT:** Some widgets have additional child Gdk windows (or real child widgets if the widget is a container) on top of their root window. In this case pointer events may come from child windows and contain wrong coordinates (relative to child window and not to the widget itself). 
The CheckPointerCoordinates workaround function checks whether the events source window is not the widgets root window and adjusts the coordinates to be relative to the widget and not to its child.
*Old message: If a widget is a container and a mouse event is raised by one of its children with own child Gdk.Window, the pointer coordinates are relative to the child and not the widget itself. In this case the pointer coordinates should be updated.*
> [Gtk] fix pointer coordinates for mouse events

- Xwt.XamMac/Xwt.Mac.CellViews/CanvasTableCell.cs
- Xwt.XamMac/Xwt.Mac.CellViews/CompositeCell.cs
- Xwt.XamMac/Xwt.Mac/BoxBackend.cs
- Xwt.XamMac/Xwt.Mac/CanvasBackend.cs
- Xwt.XamMac/Xwt.Mac/ContextBackendHandler.cs
- Xwt.XamMac/Xwt.Mac/FrameBackend.cs
- Xwt.XamMac/Xwt.Mac/GradientBackendHandler.cs
- Xwt.XamMac/Xwt.Mac/ImageBuilderBackendHandler.cs
- Xwt.XamMac/Xwt.Mac/ImageHandler.cs
- Xwt.XamMac/Xwt.Mac/LinkLabelBackend.cs
- Xwt.XamMac/Xwt.Mac/MacDesktopBackend.cs
- Xwt.XamMac/Xwt.Mac/MacEngine.cs
- Xwt.XamMac/Xwt.Mac/PathBackendHandler.cs
- Xwt.XamMac/Xwt.Mac/ScrollViewBackend.cs
- Xwt.XamMac/Xwt.Mac/SliderBackend.cs
- Xwt.XamMac/Xwt.Mac/TextLayoutBackendHandler.cs
- Xwt.XamMac/Xwt.Mac/TreeViewBackend.cs
- Xwt.XamMac/Xwt.Mac/Util.cs
- Xwt.XamMac/Xwt.Mac/ViewBackend.cs
- Xwt.XamMac/Xwt.Mac/WindowBackend.cs
* NSAttributedString constants have moved
* `System.Drawing.*F` to `CoreGraphics.CG*` conversions are gone
This will break the build with older versions. The conversions are fine but renamed constants won't work.
> Fix build with Xamarin.Mac 2.0

- TestApps/Samples/Samples/TextInput.cs
- Xwt.Gtk/Xwt.GtkBackend/Gtk2Extensions.cs
- Xwt.Gtk/Xwt.GtkBackend/Gtk3Extensions.cs
- Xwt.Gtk/Xwt.GtkBackend/GtkWorkarounds.cs
- Xwt.Gtk/Xwt.GtkBackend/WidgetBackend.cs
- Xwt.Gtk/Xwt.GtkBackend/WidgetBackendGtk2.cs
- Xwt.Gtk/Xwt.GtkBackend/WidgetBackendGtk3.cs
- Xwt.WPF/Xwt.WPFBackend/WidgetBackend.cs
- Xwt/Xwt.Backends/IWidgetBackend.cs
- Xwt/Xwt.csproj
- Xwt/Xwt/TextInputEventArgs.cs
- Xwt/Xwt/Widget.cs
Consistency: rename PreviewTextInput event to TextInput
* Xwt has no preview events. To stop an event, the Handled property of the event arguments object should be used.
GTK: adds TextInput event support
* different implementation for Editable and non-Editable widgets
* Gtk.Editable (like Entry, TextView, etc.): simply handle TextInserted event
* Other widgets: use Gtk.IMMulticontext to get text input directly from the system IM
> TextInput event optimization

- TestApps/Samples/Samples/MenuSamples.cs
- Xwt/Xwt/RadioButtonMenuItem.cs
The group handling of RadioButton menu items relies on the Clicked event, which is disabled by default. This patch enables the Clicked event even if it is not subscribed. An extended Menu example is included, too.
@slluis: is this the right way to do it?
(closes #256)
> Fix RadioButtonMenuItem group handling

- TestApps/Samples/MainWindow.cs
- TestApps/Samples/Samples.csproj
- TestApps/Samples/Samples/ListView1.cs
- TestApps/Samples/Samples/ListViewCellBounds.cs
- TestApps/Samples/Samples/TreeViewCellBounds.cs
- Xwt.Gtk/Xwt.GtkBackend.CellViews/Gtk3CellRendererCustom.cs
- Xwt.Gtk/Xwt.GtkBackend/Gtk3Extensions.cs
- Xwt.Gtk/Xwt.GtkBackend/ListViewBackend.cs
- Xwt.Gtk/Xwt.GtkBackend/TableViewBackend.cs
- Xwt.Gtk/Xwt.GtkBackend/TreeViewBackend.cs
- Xwt.WPF/Xwt.WPFBackend/ListBoxBackend.cs
- Xwt.WPF/Xwt.WPFBackend/ListViewBackend.cs
- Xwt.WPF/Xwt.WPFBackend/TreeViewBackend.cs
- Xwt.XamMac/Xwt.Mac.CellViews/CellViewBackend.cs
- Xwt.XamMac/Xwt.Mac.CellViews/CompositeCell.cs
- Xwt.XamMac/Xwt.Mac/ListViewBackend.cs
- Xwt.XamMac/Xwt.Mac/TableViewBackend.cs
- Xwt.XamMac/Xwt.Mac/TreeViewBackend.cs
- Xwt/Xwt.Backends/IListBoxBackend.cs
- Xwt/Xwt.Backends/IListViewBackend.cs
- Xwt/Xwt.Backends/ITreeViewBackend.cs
- Xwt/Xwt/ListBox.cs
- Xwt/Xwt/ListView.cs
- Xwt/Xwt/TreeView.cs
This PR adds the already known ListView cell bounds retrieval functions to ListBox and TreeView. Additionally complete row (not only cell) bounds can be retrieved. ListView/TreeView examples included.
Backend implementations/support:
* Gtk: completely rewritten
* now with real Gtk3 support
* more native position calculation without static paddings
* real data is loaded for calculation
* includes #432 for better ```GetRowAtPosition``` support
* Mac: bounds always include margins (background bounds). Everything else works as expected (tested in VM, needs more testing on a real machine).
* Wpf: ~~still TODO!~~ done in c5b4130
* static implementation by loading fixed FrameworkElement children
* the view layout hierarchy may not change
It could be a more consequent solution for #422.
> Extend Tree/List cell bounds API, various Gtk fixes, Mac impl.

- TestApps/Samples/Samples/DatePickerSample.cs
- Xwt.Gtk/Xwt.GtkBackend/DatePickerBackend.cs
- Xwt.WPF/Xwt.WPFBackend/DatePickerBackend.cs
- Xwt.XamMac/Xwt.Mac/DatePickerBackend.cs
- Xwt.XamMac/Xwt.Mac/Util.cs
- Xwt/Xwt.Backends/IDatePickerBackend.cs
- Xwt/Xwt/DatePicker.cs
This PR adds DatePickerStyle support to Gtk and Mac backends, and includes many fixes in the backend implementations.
* GTK:
* fix component selection
* fix (keep) seconds when other component chages
* fix keyboard input (incl. arrow keys and separators)
* fix mouse selection
* add internationalization support
* use localized separators
* use localized component order
* no 12/24 support
* add DatePickerStyle support (show only relevant components)
* add clipboard support
* MAC:
* add DatePickerStyle support
* fix DatePicker timezone conversion
For WPF we still need a useful DateTimePicker component. Maybe something external from NuGet?
> Refine DatePicker API and impement DatePickerStyle support [Gtk][Mac]

- Xwt.XamMac/Xwt.Mac/MacEngine.cs
Use the NSAppDelegate protocol methods to emit events for applicationShouldTerminate:, applicationDidUnhide: and
application:openFiles: It then hooks into NSAppleEventManager to listen for GetURL and emits an event for that
> [Mac] Add some events to AppDelegate

- TestApps/Samples/MainWindow.cs
- TestApps/Samples/Samples.csproj
- TestApps/Samples/Samples/FontSelectorSample.cs
- TestApps/Samples/Samples/Windows.cs
- Xwt.Gtk/Xwt.Gtk.csproj
- Xwt.Gtk/Xwt.Gtk3.csproj
- Xwt.Gtk/Xwt.GtkBackend/FontSelectorBackend.cs
- Xwt.Gtk/Xwt.GtkBackend/Gtk3FontChooserDialog.cs
- Xwt.Gtk/Xwt.GtkBackend/GtkEngine.cs
- Xwt.Gtk/Xwt.GtkBackend/SelectFontDialogBackend.cs
- Xwt.Mac/Xwt.Mac.csproj
- Xwt.XamMac/Xwt.Mac/FontBackendHandler.cs
- Xwt.XamMac/Xwt.Mac/MacEngine.cs
- Xwt.XamMac/Xwt.Mac/SelectFontDialogBackend.cs
- Xwt.XamMac/Xwt.XamMac.csproj
- Xwt/Xwt.Backends/IFontSelectorBackend.cs
- Xwt/Xwt.Backends/ISelectFontDialogBackend.cs
- Xwt/Xwt.csproj
- Xwt/Xwt/FontSelector.cs
- Xwt/Xwt/SelectFontDialog.cs
Adds a new FontSelector widget and a SelectFontDialog. Both have their own XwtWidgetBackend based implementations like ColorSelector (native backends are coming).
Backend compatibility:
* WPF: needs ~~#441~~, #442 
* GTK: works out of the box
* MAC: works after ~~#426~~, ~~#446~~ and ~~#447~~
Examples included. This PR includes ~~#450~~ (I've created a separate PR for better overview, since the other contains important fixes, that do not depend on this one.)
> Add FontSelector widget and SelectFontDialog

- Xwt.Gtk/Xwt.GtkBackend/ClipboardBackend.cs
- Xwt/AssemblyInfo.cs
This fixes `Clipboard.GetImage()` for the Gtk backend.
I have made visible the internal methods from the Xwt project for Xwt.Gtk. This is a requirement to access to the internal constructor of `Image` that accepts `GtkImage` objects (`clipboard.WaitForImage ()` returns a `Gtk.PixBuf` object). I am not sure if this is the best approach but it's working for me. I have copied the public key from a comment in *Xwt.Gtk/AssemblyInfo.cs*.
> Fix getting images from clipboard in Gtk

- TestApps/Samples/Samples/MenuSamples.cs
- Xwt.Gtk/Xwt.GtkBackend/MenuBackend.cs
- Xwt.WPF/Xwt.WPFBackend/MenuBackend.cs
- Xwt.WPF/Xwt.WPFBackend/MenuItemBackend.cs
- Xwt.XamMac/Xwt.Mac/MenuBackend.cs
- Xwt/Xwt.Backends/IMenuBackend.cs
- Xwt/Xwt/Menu.cs
The new `Menu.Font` property allows to modify the font in menus. The font will be applied on all items of a menu, but not on submenus, so each new `Menu` instance will start with the default system font.
Includes WPF/GTK/MAC implementations.
(fixes #569)
> Add new Menu.Font property

- Xwt.Gtk/Xwt.GtkBackend/PopoverBackend.cs
Showing a Popover window and then disposing it when it is closed would leave the Popover window in memory if its TransientFor window was not closed. This was because the event handler added to the TransientFor window's FocusInEvent was not removed when the Popover was disposed.
> [Gtk] Fix FocusInEvent keeping Popover in memory after it is disposed.

- Xwt/Xwt.Drawing/Font.cs
- Xwt/Xwt/Toolkit.cs
This fixes two different bugs with Fonts:
1. when setting the font size, `WithSize` should use its own `ToolkitEngine` instead of `Toolkit.CurrentEngine`
2. When a system font is being validated and initialized for a different toolkit, only its family name should be checked whether its a system font or not and the actual settings should be copied from the source backend. Otherwise a new font with the original system font family was created, which is not necessarily the system font of the target toolkit and which may not be even available for it (i.e. San Francisco fonts on OSX 10.11, which is not supported by Pango).
> Fix font toolkit validation

- Xwt/Xwt/Window.cs
Basically, this disposes of the Window content in the Xwt hierarchy.
Previously, this was insufficient, while it _did_ remove the Gtk
references, subscribing to an eventhandler and overriding Dispose on a
widget that's placed in a Xwt Window will cause the widget to not be
disposed, thus leak memory.
> [Window] Fix leak of whole dialog/window content.

- Xwt/Xwt.Drawing/Font.cs
For some fonts a valid registered name can include the font settings (weight, size, etc.). In such cases the parser fails to retrieve the font from the backend by stripping the settings from the name.
Fix: the name parser should try to validate the full name including provided settings first.
Examples:
* "Arial Rounded MT Bold", "Bold" is part of the font name and the registered weight is normal (there is only a "Regular" font face registered)
* "Bodoni 72": 72 is not the size but part of the name
> Optimize Font.FromName parser

- Xwt.XamMac/Xwt.Mac.CellViews/CompositeCell.cs
- Xwt.XamMac/Xwt.Mac/NSTableViewBackend.cs
- Xwt.XamMac/Xwt.Mac/TreeViewBackend.cs
Previousy the height was fixed to the height of the highest row, because NSTableView/NSOutlineView use always the fixed RowHeight property in the deprecated NSCell based mode.
Now we use protocol delegates to calculate the height for each row dynamically.
The difference can be verified in the FontSelector widget, where the rows have different heights due to different font metrics. The Font parsing bug (fixed in #544) makes it even worse by rendering some fonts with extremely large sizes.
Before:
After:
> [Mac] Support different row heights in Lists/Trees

- TestApps/Samples/Samples/FontSelectorSample.cs
- Xwt.XamMac/Xwt.Mac/FontBackendHandler.cs
- Xwt/Xwt.Backends/FontBackendHandler.cs
This PR adds some optimizeation to the Font handling in XWT.
* better handling of default font names
* Mac backend supports (comma separated) alternative names when creating new fonts
* Adds system fonts to the FontSelector example
> Optimize default font handling

- Xwt/Xwt.Backends/FontBackendHandler.cs
- Xwt/Xwt.Drawing/Font.cs
- Xwt/Xwt/Toolkit.cs
* always call InitForToolkit when font is being validated
* replace the whole font object if it is a system font reference
* let the FontBackendHandler do the system font conversions
> Fix Font backend switching on Toolkit changes

- Xwt.XamMac/Xwt.Mac/PasswordEntryBackend.cs
- Xwt.XamMac/Xwt.Mac/TextEntryBackend.cs
- Xwt.XamMac/Xwt.Mac/WidgetView.cs
* fixes frame drawing and text alignment for custom heights
* removes the 1px white border around the border (appeared sporadically)
* allows to set the background color correctly inside the frame only
* adds TextEntry.SelectionChanged implementation
@alanmcgovern: this fix optimizes some parts of 1e31b7315aa3e528456a586fae56dab7b96103f4, can you review? I hope it doesn't break anything.
Some screenshots:
Before:
After:
> [Mac] Optimize mac textentry frame, alignment and selection

- Xwt.Gtk/Xwt.GtkBackend/Gtk3Extensions.cs
- Xwt.Gtk/Xwt.GtkBackend/ImageHandler.cs
For Gtk3 (as well as for Gtk2), draws a custom Gtk.MissingIcon if Stock icon cannot be loaded
> [GtkBackend] Add custom Gtk.MissingIcon for Gtk3

- Xwt.Gtk.Mac/GtkMacPopoverBackend.cs
- Xwt.Gtk.Mac/GtkQuartz.cs
- Xwt.Gtk.Mac/Xwt.Gtk.Mac.csproj
- Xwt.Gtk/Xwt.GtkBackend/PopoverBackend.cs
This PR removes the border around the Gtk Popover window on Mac.
Before:
After:
> [Gtk.Mac] Remove broken Popover window border

- Xwt.Gtk/Xwt.Gtk3.csproj
- Xwt.Gtk/Xwt.GtkBackend/GtkWorkarounds.cs
Fixes 2 things:
1) Build output for Gtk3 Release was set to "Debug" folder instead of "Release"
2) Gtk.Object does not exist in Gtk 3, GLib.Object does however exist in both Gtk 2 and 3
> Fix Gtk3 Build

- Xwt/Xwt.Drawing/Font.cs
- Xwt/Xwt.Drawing/TextLayout.cs
- Xwt/Xwt/Toolkit.cs
I have missed to commit some bits required for #583 and here are the missing parts:
* TextLayout should always validate a Font (especially in mixed environments)
* When switching a Font backend and the specific font is missing in the target toolkit, at least the font settings should be applied on the default system font.
* Sytem font swapping should respect the font settings (due to a broken commit, I accidentially reverted that part)
> Fix font backend switching Pt.2

- Xwt.XamMac/Xwt.Mac/MacDesktopBackend.cs
There's a type inconsistency in the property `NSEvent.CurrentMouseLocation` from MonoMac and XamMac, preventing the MonoMac project to build.
> Fix Mac Backend for current mouse location

- Xwt.XamMac/Xwt.Mac/MacEngine.cs
Fixed AppDelegate.OpenUrl not being invoked when the application is being launched because an url has been opened which has been specified in the Info.plist file
> [Mac] Fixed AppDelegate.OpenUrl not being invoked

- Xwt.Gtk/Xwt.GtkBackend/GtkWebKitMini.cs
- Xwt.Gtk/Xwt.GtkBackend/ScrollViewBackend.cs
WebKitGtk supports native scrolling and should not be packed into a Gtk.Viewport.
This PR fixes #604, but the horizontal scrolling is still partially broken (the scrollbar does not disappear if the content fits the window). It seems to be related to the problems discussed here: https://lists.webkit.org/pipermail/webkit-gtk/2011-May/000512.html. A possible solution could be to listen to the `web-view-ready` event and to set a customized size request based on [WebKitWebWindowFeatures](https://webkitgtk.org/reference/webkitgtk/stable/WebKitWebWindowFeatures.html).
> [Gtk] Fix WebView scrolling

- TestApps/WpfTest/Main.cs
- Xwt.WPF/Xwt.WPFBackend/WebViewBackend.cs
The WPF WebView has only a very limited API and hides its internal IWebBrowser2 (ActiveX) control. This PR optimizes the WPF WebView backend, by trying to access the ActiveX control using reflection.
* use reflection (without MSHTML reference) to handle the document title
* suppress JS Error messages (using reflection again)
* add example on how to switch to a different WebView IE Emulation mode (i.e. Internet Explorer 11)
> [Wpf] Optimize wpf webview

- TestApps/Samples/Samples/WebViewSample.cs
- Xwt.Gtk.Mac/WebViewBackend.cs
- Xwt.Gtk.Windows/WebViewBackend.cs
- Xwt.Gtk.Windows/Win32.cs
- Xwt.Gtk.Windows/Xwt.Gtk.Windows.csproj
- Xwt.Gtk/Xwt.GtkBackend/GtkWebKitMini.cs
- Xwt.Gtk/Xwt.GtkBackend/WebViewBackend.cs
- Xwt.WPF/Xwt.WPF.csproj
- Xwt.WPF/Xwt.WPFBackend.Interop/IDocHostUIHandler.cs
- Xwt.WPF/Xwt.WPFBackend.Interop/NativeMethods.cs
- Xwt.WPF/Xwt.WPFBackend/WebViewBackend.cs
- Xwt.XamMac/Xwt.Mac/WebViewBackend.cs
- Xwt/Xwt.Backends/IWebViewBackend.cs
- Xwt/Xwt/WebView.cs
This PR includes following changes to WebView:
* `ContextMenuEnabled` property: disables the context menu if set to `false`
* `CustomCss` property: injects custom CSS code into the loaded HTML page. **Gtk/Mac:** For now the the custom css code is simply added to the DOM at the beginning of the `head` section. **Windows:** Uses IDocHostUIHandler API. In the future it could inject the style using a special API without DOM modification if supported by the backend (already done on Windows, Linux: WebKitGtk2 supports this)
* `ScrollBarsEnabled` property: disables native WebView scrolling if set to `false` and supported by the backend (~~doesn't work with Wpf~~). This is enabled by default (like before) and disabling the native scrolling is very experimental.
* many small fixes on `Windows`
> WebView fixes / new features

- Xwt/Xwt/TreeStore.cs
This traverses the TreeStore to find the TreeNavigator of the first item that contains a specified value in the data field.
One use case: Getting the TreePosition of the navigator and then select the corresponding row.
> Finding TreeNavigators by value in TreeStore.

- Xwt/Xwt/TreeNavigator.cs
The parameter `int row` is not used in the overloads, and only the overloads for 2 and 3 values use it.
In order not to break existing code, the original signatures are still there, but call the new methods and are marked with `ObsoleteAttribute`.
> Consistent overloads for TreeNavigator.SetValues().

- Xwt.WPF/Xwt.WPFBackend/ListBoxBackend.cs
- Xwt.WPF/Xwt.WPFBackend/ListViewBackend.cs
On GTK, the RowActivated event of a ListBox is raised when the user performs a double-click on a row. To mimic this behavior on WPF, I used the MouseDoubleClick event of a System.Windows.Controls.ListBox.
References:
http://en.wikibooks.org/wiki/GTK%2B_By_Example/Tree_View/Events#Double-Clicks_on_a_Row
http://docs.go-mono.com/?link=E%3aGtk.TreeView.RowActivated
https://msdn.microsoft.com/en-us/library/system.windows.controls.control.mousedoubleclick(v=vs.110).aspx
> [WPF] ListBox and ListView: add support to RowActivated event

- Xwt.Gtk/Xwt.GtkBackend/GtkWorkarounds.cs
- Xwt.Gtk/Xwt.GtkBackend/RichTextViewBackend.cs
- Xwt.WPF/Xwt.WPFBackend/ExRichTextBox.cs
- Xwt.WPF/Xwt.WPFBackend/LabelBackend.cs
- Xwt.WPF/Xwt.WPFBackend/RichTextViewBackend.cs
- Xwt.XamMac/Xwt.Mac/RichTextViewBackend.cs
- Xwt/Xwt.Backends/IRichTextViewBackend.cs
- Xwt/Xwt.Formats/MarkupTextFormat.cs
- Xwt/Xwt.csproj
- Xwt/Xwt/RichTextView.cs
This PR adds Markup support to `RichTextView`. This includes a new `MarkupTextFormat` to parse the Markup and a new `MarkupView` widget (works similar to `MarkdownView`).
Additionally the new Parser supports Paragraphs which will be emitted for every double line break (`\n\n`).
Additional Features:
* `RichTextView.Selectable`: `false` disables selection mode and makes the RichTextView look like a label - 0cbe062
* `RichTextView.LineSpacing` can be used to change the spacing between the lines/paragraphs - 9140554
Bugfixes/Optimizations:
* `BackgroundColor` fixed on Gtk/Mac - 23df2cf / 8817f91
* `strikethrough` span tag fixed on Wpf - 40f5c55
* No Xml parsing in Wpf (use `FlowDocument` API directly) -  	fb10edf
* Fixed Pango.AttrList leak (thx @Therzok) - c8e0627
> Markup support for RichTextView (+ some new features)

- TestApps/Samples/Samples/Windows.cs
- Xwt.Gtk/Xwt.GtkBackend/DialogBackend.cs
- Xwt.WPF/Xwt.WPFBackend/DialogBackend.cs
- Xwt.XamMac/Xwt.Mac/DialogBackend.cs
- Xwt/Xwt.Backends/IDialogBackend.cs
- Xwt/Xwt/Dialog.cs
This PR includes the following new Dialog Button features:
1. `DialogButton.PackOrigin` can be used to align buttons on the left side of the button area in a dialog (this is similar to Box packing)
2. `Dialog.CommandActivated` event can be subscribed to intercept command activation and to prevent a Dialog from responding (returning with the activated command from the loop) by setting the `Handled` property of the EventArgs object
3. `Dialog.DefaultCommand` can be set to make a command the default button of a dialog. It depends on the toolkit how the default command works (in most cases the default button is highlighted and will be activated when the user presses the `Return` key)
> Extended dialog buttons

- Xwt.WPF/Xwt.WPFBackend/WidgetBackend.cs
- Xwt.WPF/Xwt.WPFBackend/WindowFrameBackend.cs
- Xwt/Xwt.Backends/IDispatcherBackend.cs
- Xwt/Xwt.csproj
- Xwt/Xwt/Application.cs
- Xwt/Xwt/Toolkit.cs
- Xwt/Xwt/XwtComponent.cs
This PR includes the following optimizations/features:
* new `Application.InvokeAsync` functions which return an observable `Task`
* new `XwtComponent.InvokeAsync` functions to invoke code in the context of a specific Xwt Component/Widget (uses the Toolkit assigned to the component and optionally uses component specific UI sync logic)
* new `IDispatcherBackend` interface for backend specific UI synchronization logic. Inludes WPF support to `DispatcherObject.Dispatcher`.
Especially in Dialogs (and modal Windows in general) `Window.InvokeAsync` should be the preferred synchronization method, because WPF dialogs could run on a different (not the main UI) thread where `Application.Invoke` may block/fail silently.
> Optimizations to the UI thread synchronization API

- Xwt.Gtk/Xwt.GtkBackend/AlertDialogBackend.cs
- Xwt.WPF/Xwt.WPFBackend/AlertDialogBackend.cs
- Xwt.XamMac/Xwt.Mac/AlertDialogBackend.cs
- Xwt.XamMac/Xwt.Mac/DialogBackend.cs
- Xwt/Xwt/CanvasCellView.cs
`Toolkit.CurrentEngine` should only be used if no `ApplicationContext` an no direct backend ref is available.
This fixes usage of a wrong toolkit in some cross-toolkit scenarios.
> Use ApplicationContext.Toolkit where appropriate

- Xwt.Gtk.Mac/GtkMacOpenFileDialogBackend.cs
- Xwt.Gtk.Mac/GtkMacSaveFileDialogBackend.cs
- Xwt.Gtk.Mac/GtkMacSelectFolderBackend.cs
- Xwt.Gtk/Xwt.GtkBackend/FileDialogBackend.cs
- Xwt.Gtk/Xwt.GtkBackend/GtkAlertDialog.cs
- Xwt.XamMac/Xwt.Mac/FileDialogBackend.cs
- Xwt.XamMac/Xwt.Mac/SaveFileDialogBackend.cs
- Xwt.XamMac/Xwt.Mac/SelectFolderDialogBackend.cs
- Xwt/Xwt.csproj
- Xwt/Xwt/Application.cs
- Xwt/Xwt/ColorSelector.cs
- Xwt/Xwt/Command.cs
- Xwt/Xwt/FontSelector.cs
- Xwt/Xwt/ITranslationCatalog.cs
- Xwt/Xwt/SelectFontDialog.cs
This PR makes internal Xwt strings translatable though a custom `Xwt.ITranslationCatalog` implementation in `Application.TranslationCatalog`. The default implementation simply returns the same unteranslated string.
(closes #627)
> Add translation support

- Xwt.XamMac/Xwt.Mac/ImageHandler.cs
- Xwt/Xwt.Drawing/DrawingImage.cs
This fixes two issues:
1. When drawing more than one custom image with different styles using the same drawing context, the context styles need to be reset each time.
2. `ImageBackendHandler.ConvertToBitmap` may be called with a slightly modified `ImageDescription` which is being passed into the `CustomImage.DrawInContext` call and needs to be used instead the original `CustomImage.Image`. The issue can be reproduced in the ColorSelector example.
> Fix custom image drawing issues

- Xwt.XamMac/Xwt.Mac/SpinButtonBackend.cs
The sizing and placement of the inner input field needs
to be done by the main container widget during the
ResizeSubviewsWithOldSize call while the main
widget has its final size.
> [Mac] Fix SpinButton sizing and innner allocations

- Testing/Tests/WidgetTests.cs
- Xwt.Gtk/Xwt.GtkBackend/WidgetBackend.cs
- Xwt.WPF/Xwt.WPFBackend/WidgetBackend.cs
- Xwt.XamMac/Xwt.Mac/Util.cs
- Xwt.XamMac/Xwt.Mac/ViewBackend.cs
- Xwt/Xwt.Backends/IWidgetBackend.cs
- Xwt/Xwt/Widget.cs
The new ParentBounds and WindowBounds properties and point conversion methods make it possible to retrieve bounds and coordinates relative to a parent widget or the root window of a widget.
New:
* `Widget.ParentBounds`: bounds of a widget relative to its parent widget
* `Widget.WindowBounds`: bounds of a widget relative to its parent window
* `Widget.ConvertToParentCoordinates(Point p)`: convert widget coordinates to parent coordinates
* `Widget.ConvertToWindowCoordinates(Point p)`: convert widget coordinates to window coordinates
> Add ParentBounds and WindowBounds

- Xwt.XamMac/Xwt.Mac/Util.cs
- Xwt.XamMac/Xwt.Mac/WidgetView.cs
It is not guaranteed that a NSEvent.Window is the
parent NSWindow of the current View. If the event
comes from a foreign NSWindow, we need to
convert the relative pointer location.
> [Mac] Fix mouse pointer location from foreign windows

- Testing/Tests/FontTests.cs
- Xwt.Gtk/Xwt.GtkBackend/FontBackendHandler.cs
- Xwt/Xwt.Drawing/Font.cs
This PR fixes some issues and failing font tests introduced in #544. Additionally it includes new tests for special font names.
> Fix special font name parsing and font unit tests

- Xwt.XamMac/Xwt.Mac/ButtonBackend.cs
- Xwt.XamMac/Xwt.Mac/ComboBoxBackend.cs
- Xwt.XamMac/Xwt.Mac/GtkQuartz.cs
- Xwt.XamMac/Xwt.Mac/LabelBackend.cs
- Xwt.XamMac/Xwt.Mac/PopoverBackend.cs
- Xwt.XamMac/Xwt.Mac/SeparatorBackend.cs
- Xwt.XamMac/Xwt.Mac/SliderBackend.cs
- Xwt.XamMac/Xwt.Mac/SpinButtonBackend.cs
- Xwt.XamMac/Xwt.XamMac.csproj
This PR includes various PopoverBackend fixes:
* `Closed` event was missing
* Resizing fixed
* `Padding` was missing
* `BackgroundColor` fixed
* Support for custom NSAppearance
* Positioning fixed
The last commit 29c280388e0679b9514ddf60daa83e088a2e6539 allows to attach a Popover to a Gtk based Widget.
> Optimize Popover impl. + support Gtk based reference widgets

- Xwt.XamMac/Xwt.Mac/ScrollViewBackend.cs
- Xwt.XamMac/Xwt.Mac/Util.cs
This PR fixes issues with ScrollView sizing and adds some missing backend features.
Fixed Sizing:
* Support `Margin` and `WidgetPlacement` of the child using `WidgetPlacementWrapper`
* Calculate preferred size based on child size (incl. placement request) and the current scrolling policies.
* Reallocate based on new preferred size calculation and take own size requisition into account.
Missing Features:
* `BorderVisible` property
* `VisibleRect` property
* `VisibleRectChanged` event
> Optimize XamMac ScrollView

- Xwt.XamMac/Xwt.Mac/LabelBackend.cs
- Xwt/Xwt/Label.cs
Fixes wrong label size after updating `Label.Markup` and rendering/sizing issues with formatted text inside labels on Mac.
> Fix label markup sizing

- Xwt.XamMac/Xwt.Mac/Util.cs
Some system colors can not be calibrated and UsingColorSpace returns null, causing an NRE.
Use CGColor in this case, which should match the device already.
> [Mac] Fix NRE in System NSColor to Xwt.Color conversion

- Xwt.XamMac/Xwt.Mac/FontBackendHandler.cs
- Xwt.XamMac/Xwt.Mac/TextLayoutBackendHandler.cs
- Xwt.XamMac/Xwt.Mac/Util.cs
* AddAttribute/ClearAttributes support
* Apply TextAttributes supported by CoreText
> [Mac] Fix some missing TextLayout.Markup features

- Xwt.XamMac/Xwt.Mac/LabelBackend.cs
- Xwt.XamMac/Xwt.Mac/Util.cs
NSTextField.Alignment has no effect if
NSTextField.AttributedString is being used
for Markup. Alignment needs to be added to
the NSAttributedString with an appropriate
NSParagraphStyle.
> [Mac] fix Label alignment with Label.Markup

- TestApps/Samples/MainWindow.cs
- TestApps/Samples/Samples.csproj
- TestApps/Samples/Samples/PopupWindows.cs
- Xwt.Gtk/Xwt.Gtk.csproj
- Xwt.Gtk/Xwt.Gtk3.csproj
- Xwt.Gtk/Xwt.GtkBackend/Gtk2PopoverWindow.cs
- Xwt.Gtk/Xwt.GtkBackend/Gtk3PopoverWindow.cs
- Xwt.Gtk/Xwt.GtkBackend/GtkEngine.cs
- Xwt.Gtk/Xwt.GtkBackend/PopoverBackend.cs
- Xwt.Gtk/Xwt.GtkBackend/PopupWindowBackend.cs
- Xwt.Gtk/Xwt.GtkBackend/UtilityWindowBackend.cs
- Xwt.Gtk/Xwt.GtkBackend/WindowBackend.cs
- Xwt.WPF/Xwt.WPFBackend/WPFEngine.cs
- Xwt.WPF/Xwt.WPFBackend/WindowBackend.cs
- Xwt.WPF/Xwt.WPFBackend/WindowFrameBackend.cs
- Xwt.XamMac/Xwt.Mac/MacEngine.cs
- Xwt.XamMac/Xwt.Mac/PopupWindowBackend.cs
- Xwt.XamMac/Xwt.Mac/WindowBackend.cs
- Xwt.XamMac/Xwt.XamMac.csproj
- Xwt/Xwt.Backends/IPopupWindowBackend.cs
- Xwt/Xwt.Backends/IUtilityWindowBackend.cs
- Xwt/Xwt.Backends/IWindowBackend.cs
- Xwt/Xwt.csproj
- Xwt/Xwt/PopupWindow.cs
- Xwt/Xwt/UtilityWindow.cs
- Xwt/Xwt/WidgetSpacing.cs
- Xwt/Xwt/Window.cs
This PR adds an `Xwt.PopupWindow` window (replacing the dummy Xwt.PopupWindow).
The PopupWindow is a special window type (based on `Xwt.Window`) which can be used to show custom Panels, custom Tooltips, custom Menus or highly customized windows.
By default a PopupWindow is a so called Utility Window, but it can also be created with an additional `PopupType` parameter to change the default behavior of the Popup:
* `PopupType.Utility`:
Default Utility window (Cocoa: `NSPanel`, Gtk/Wpf: default window with utility style)
* `PopupType.Tooltip`:
A special undecorated utility/popup window with support for background colors with alpha channel.
Depending on the toolkit capabilities it may have a different pointer handling or animation.
* `PopupType.Menu`:
In most cases same as `PopupType.Tooltip` …
> Add PopupWindow

- Xwt.Gtk/Xwt.GtkBackend/TableViewBackend.cs
setting an custom HeaderView results in an invisible Header
Solution:
Show() has to be called 
(see: http://stackoverflow.com/questions/24698901/header-widget-in-gtk-treeviewcolumn)
> [Gtk] TableViewBackend: custom HeaderView is not visible

- Xwt.XamMac/Xwt.Mac/ViewBackend.cs
In some rare cases a view and its superview both implement IViewObject
and additionally share the same Backend (for eaxmple a custom widget
inside an alignement container), which results in an infite loop when
Backend.ParentIsSensitive is called.
The workaround is to not rely on Superview being a IViewObject
and its Backend.Widget to be the real parent, but to use
Widget.Superview only to walk up the widget hierarchy.
> [Mac] Fix stack overflow in ViewBackend.ParentIsSensitive

- Xwt.Gtk/Xwt.GtkBackend.CellViews/CellViewBackend.cs
- Xwt.WPF/Xwt.WPF.csproj
- Xwt.WPF/Xwt.WPFBackend.CellViews/CanvasCellViewBackend.cs
- Xwt.WPF/Xwt.WPFBackend.CellViews/CellViewBackend.cs
- Xwt.WPF/Xwt.WPFBackend.CellViews/CheckBoxCellViewBackend.cs
- Xwt.WPF/Xwt.WPFBackend.CellViews/TextCellViewBackend.cs
- Xwt.WPF/Xwt.WPFBackend.Utilities/CellUtil.cs
- Xwt.WPF/Xwt.WPFBackend/ComboBoxBackend.cs
- Xwt.WPF/Xwt.WPFBackend/DataConverter.cs
- Xwt.WPF/Xwt.WPFBackend/ListBoxBackend.cs
- Xwt.WPF/Xwt.WPFBackend/ListViewBackend.cs
- Xwt.WPF/Xwt.WPFBackend/TreeViewBackend.cs
- Xwt.WPF/Xwt.WPFBackend/WidgetBackend.cs
- Xwt/Xwt/CellView.cs
This is an optimized approach compared to #435.
Its based on a complete Enable-/DisableEvent implementation in the base CellView which is passed to the backends as intended.
Gtk: I've added the missing events to the backend. The implementation is based on the root TableView events with mouse position checks (CellRenderer has no own events)
Wpf: the events are enabled in the element factory by default and the backend checks whether an event is enabled or not. It is not possible (?) to dynamically enable/disable events for each cell, since the cell generation is handeled by the FrameworkElementFactory which is sealed after initialization. Additionally it includes a little fix for the custom cell (find the working example in the example app).
Mac: still TODO
> Implement cellview events + [Gtk][Wpf] support

- Xwt.XamMac/Xwt.Mac/NSApplicationInitializer.cs
4a4476f5192438e64a5643b8ee9731b7fc0e678f broke the build with older Xamarin.Mac versions (any before https://github.com/xamarin/xamarin-macios/commit/0963ba1e755c0f2a75bae6a387ad3f0ad8eba650, which is included in XM 3.4+ only)
> [Mac] Fix build with XamMac older than 3.4

- Xwt.XamMac/Xwt.Mac/NSTableViewBackend.cs
- Xwt.XamMac/Xwt.Mac/OutlineViewBackend.cs
NSTableView autosizes its colums with enabled
Autoresizing only on initialization but not on
data changes. This patch forces the view to
recalculate column sizes of expanding columns,
and additionally enforces a fitting width for
not resizable columns.
> [Mac] Force NSTableView to autoresize columns

- Xwt.WPF/Xwt.WPFBackend.CellViews/CheckBoxCellViewBackend.cs
- Xwt.WPF/Xwt.WPFBackend.Utilities/CellUtil.cs
The `Checked` and `Unchecked` events are bound to the dependency properties and occur after the CheckBox has been toggled and the bound field set to the new state. This makes it impossible to implement own `Toggled` logic in the `CheckBoxCellView.Toggled` handler.
This patch introduces a new `CheckBox.Toggle` routed event which is raised before the default `OnToggle ()` logic, which can be stopped by setting `RoutedEventArgs.Handled`. The `CheckBoxCellViewBackend` uses the new logic to allow custom toggle logic on the Frontend side.
Additionally this patch fixes the `AllowMixedField` and `StateField` bindings using a custom `CheckBoxState` converter, which play together with the fixed Toggle implementation.
> [WPF] Fix CheckBoxCell Toggle and Mixed state handling

- Xwt.WPF/Xwt.WPFBackend/SpinnerBackend.cs
The WPF SpinnerBackend had a fixed size of 25pt. This Patch adds `MinWidth`/`MinHeight` and `WidthRequest`/`HeightRequest` support when the widget is being measured by WPF (fallbacks to the default 25pt if no request is specified) and makes use of the given (but not used before due to the fixed size) scaling implementation of `ArrangeOverride`.
> [WPF] Make SpinnerBackend scalable

- Xwt.XamMac/Xwt.Mac/ImageViewBackend.cs
This Patch simply packs the NSImageView into an additional CustomAlignedContainer which will handle the default widget events.
> [Mac] Use CustomAlignedContainer to handle ImageViewBackend events

- Xwt.Gtk/Xwt.GtkBackend.CellViews/CustomCellRendererText.cs
It is not guaranteed that a cell has only a markup or a text data field. Sometimes it can be useful to have both (expandable trees). In such a mixed mode we need to reset the Pango attributes when setting the cell text.
> [Gtk] Reset CellRendererText.Attributes when using mixed text and markup data fields

- Xwt.XamMac/Xwt.Mac/RichTextViewBackend.cs
If the enclosing ScrollViews horizontal scrolling
is disabled, GetPreferredSize should not use the initial
text width in order to allow the text view to wrap
the text.
> [Mac] Fix RichTextView wrapping inside ScrollView

- Xwt.Gtk/Xwt.GtkBackend/EmbeddedWidgetBackend.cs
- Xwt.WPF/Xwt.WPFBackend/EmbedNativeWidgetBackend.cs
- Xwt.XamMac/Xwt.Mac/EmbedNativeWidgetBackend.cs
- Xwt.XamMac/Xwt.Mac/PopoverBackend.cs
- Xwt/Xwt.Backends/IEmbeddedWidgetBackend.cs
- Xwt/Xwt/Toolkit.cs
* Added a parameter to `WrapWidget` to do not reparent the nativeView.
We can’t wrap and unwrap the NSView to be used with the Popover, because this will change the parent of the window when we unwrap it, invalidating the `NSView.Window`, making NSPopover throw a NSException, due the missing NSWindow inside the NSView.
* This add a option to do not reparent the native view when Wrap/Unwrap, and get the (untouched) native view back on `Show`.
Previous related PR: https://github.com/mono/xwt/pull/668
> [Mac] Fixed crash using Popover with `NSView`.

- Xwt.Gtk/Xwt.GtkBackend/EmbeddedWidgetBackend.cs
- Xwt.WPF/Xwt.WPFBackend/EmbedNativeWidgetBackend.cs
- Xwt.XamMac/Xwt.Mac/EmbedNativeWidgetBackend.cs
- Xwt.XamMac/Xwt.Mac/PopoverBackend.cs
- Xwt/Xwt.Backends/IEmbeddedWidgetBackend.cs
- Xwt/Xwt/Toolkit.cs
backporting this so the designer doesn't crash immediately when opening it's popups: https://github.com/mono/xwt/pull/676
> D15 2 dont reparent popups

- TestApps/Samples/Samples/TreeViews.cs
- Xwt.Gtk/Xwt.GtkBackend.CellViews/CellUtil.cs
- Xwt.Gtk/Xwt.GtkBackend.CellViews/CustomCellRendererToggle.cs
- Xwt.WPF/Xwt.WPF.csproj
- Xwt.WPF/Xwt.WPFBackend.CellViews/RadioButtonCellViewBackend.cs
- Xwt.WPF/Xwt.WPFBackend.Utilities/CellUtil.cs
- Xwt.XamMac/Xwt.Mac.CellViews/CellUtil.cs
- Xwt.XamMac/Xwt.Mac.CellViews/RadioButtonTableCell.cs
- Xwt.XamMac/Xwt.XamMac.csproj
- Xwt/Xwt.Backends/IRadioButtonCellViewFrontend.cs
- Xwt/Xwt.Backends/IToggleCellViewFrontend.cs
- Xwt/Xwt.csproj
- Xwt/Xwt/RadioButtonCellView.cs
This PR adds Option-/RadioButton Cells for Lists/Tables.
Limitations:
No Grouping support as in RadioButton.
~~Issues:
WPF impl. lacks Events (like all other Cell Views) and is unusable because the user can't handle the Toggled event.~~ **EDIT:** fixed in #531
> Add RadioButtonCellView

- Xwt/Xwt/Clipboard.cs
Without this, `Clipboard.ContainsData` can return different results depending on which backend it is invoked with.
The only caveat I see with this approach is that any `Image` object returned from the Clipboard API will now have the native backend, which might be different than where it will be consumed. But since we have multi-toolkit support for images, I don't think this should be an issue.
> Always use native backend for Clipboard

- Xwt/Xwt/Toolkit.cs
If throwIfFails is false, exceptions should be ignored
as requested by the caller. Otherwise Toolkit.TryLoad
raises UnhandledException without need.
> Don't raise UnhandledException on toolkit loading failure

- Xwt.XamMac/Xwt.Mac/ContextBackendHandler.cs
- Xwt.XamMac/Xwt.Mac/ImageHandler.cs
This commit works around code that reflects a lot. NSObject.Copy() does
reflection to find the intptr constructor of an object, then uses
ConstructorInfo.Invoke to construct the NSImage.
Since we don't operate with the actual NSImage in the case we don't
have a custom image, do not create a copy, as we only need to pass in
the CGImage we get. The AsCGImage does not do any reflection, so this
should turn into faster code.
> [Mac] Optimize image drawing context.

- Xwt.WPF/Xwt.WPFBackend/WindowBackend.cs
- Xwt.XamMac/Xwt.Mac/PopupWindowBackend.cs
- Xwt/Xwt/PopupWindow.cs
- Xwt/Xwt/UtilityWindow.cs
This fixes the `PopupWindow`initialization by calling `IPopupWindowBackend.Initialize` before `IWindowFrameBackend.Initialize` and the backends should take care of the rest.
> Fix PopupWindow initialization

- Xwt.Gtk/Xwt.GtkBackend/ImageHandler.cs
On Gtk the ImageBox is a custom Gtk.DrawingArea so it needs to have an image role set for accessibility
> [a11y] Set the role of the ImageBox to an Image

- Xwt.Gtk/Xwt.GtkBackend/DatePickerBackend.cs
The adjustment is held on the SpinButton as a property, not parented, so there is no destroy event happening for the adjustment.
> [Xwt] Fix leak in DatePicker

- Xwt/Xwt.Drawing/Font.cs
This fixes a croner case on Mac where Gtkrc must define
an invalid font name, because GTK can not handle
the special .AppleSystemUIFont name.
This fixes the warning:
`Font '-apple-system-font' not available in the system. Using '.AppleSystemUIFont' instead`
> [Mac] Fix invalid -apple-system-font warning

- Xwt/Xwt.Drawing/Font.cs
The fix introduced in b9fc3ab78357c987fc43795f2197b6f75765c5e1
did not take into account that the "-apple-system-font"
may have been already detected. This can happen if the Xwt.Gtk
font backend is initialized first.
> [Mac] Fix invalid -apple-system-font warning Pt.2

- Xwt.Gtk/Xwt.GtkBackend/FileDialogBackend.cs
- Xwt.Gtk/Xwt.GtkBackend/SelectColorDialogBackend.cs
- Xwt.Gtk/Xwt.GtkBackend/SelectFontDialogBackend.cs
- Xwt.WPF/Xwt.WPFBackend/SelectColorDialogBackend.cs
- Xwt.WPF/Xwt.WPFBackend/SelectFolderDialogBackend.cs
- Xwt.WPF/Xwt.WPFBackend/Util.cs
- Xwt/Xwt/FileDialog.cs
- Xwt/Xwt/SelectColorDialog.cs
- Xwt/Xwt/SelectFolderDialog.cs
- Xwt/Xwt/SelectFontDialog.cs
This does the same what we did in #596 for (Alert-)Dialogs, but this time for the most system dialogs (file, folder, color and font selectors).
GTK: full support
MAC: TBD, parenting not implemented at all
WPF: File dialogs missing, because we use the `Microsoft.Win32.FileDialog` wrapper (instead of the underlying `System.Windows.Forms.FileDialog` implementation) which does not allow native window owners.
> Cross toolkit system dialogs

- Xwt.Gtk/Xwt.Gtk.csproj
- Xwt.Gtk/Xwt.GtkBackend/ListStoreBackend.cs
- Xwt.Gtk/Xwt.GtkBackend/TreeStoreBackend.cs
- Xwt/Xwt.csproj
- Xwt/Xwt/ListStore.cs
- Xwt/Xwt/TreeNavigator.cs
- Xwt/Xwt/TreeStore.cs
There are a few unnecessary warnings in Xwt and Xwt.Gtk which are just annoying. We're using Xwt from source currently and all of our other projects have zero warnings and will fail if any warnings are issued. It just seems like it's time to get rid of these few warnings.
> Remove old warnings in Xwt and Xwt.Gtk

- Xwt.Gtk/Xwt.GtkBackend.CellViews/CellViewBackend.cs
- Xwt.Gtk/Xwt.GtkBackend/WidgetBackend.cs
- Xwt.WPF/Xwt.WPFBackend/DataConverter.cs
- Xwt.XamMac/Xwt.Mac/ComboBoxEntryBackend.cs
- Xwt.XamMac/Xwt.Mac/NSTableViewBackend.cs
- Xwt.XamMac/Xwt.Mac/OutlineViewBackend.cs
- Xwt.XamMac/Xwt.Mac/Util.cs
- Xwt.XamMac/Xwt.Mac/WidgetView.cs
- Xwt/Xwt/ButtonEventArgs.cs
I discussed with @sevoku a while back about exposing an API to allow us to cleanly support the macos specific behaviour of displaying context menu's when the user uses `control-click`.
Docs: https://developer.apple.com/library/content/documentation/Cocoa/Conceptual/MenuList/Articles/HowMenusWork.html
Does this approach make sense to you guys? If so we'll finalise and merge it!
> Handle context menu

- Xwt.WPF/Xwt.WPFBackend/ExTreeView.cs
Manually updating the widget layout only for root elements, as children are not affected by this bug
This fixes https://bugzilla.xamarin.com/show_bug.cgi?id=58917
This closes #720
> ExTreeView: Fixed missing first root element

- Xwt.XamMac/Xwt.Mac/ContextBackendHandler.cs
This fixes the Mac backend to match the Gtk backend when drawing multi-style/resolution images with GlobalAlpha set on the context.
> [Mac] Respect GlobalAlpha when drawing custom-drawn images

- Testing/Tests/TreeViewTests.cs
- Xwt.WPF/Xwt.WPFBackend/ExTreeView.cs
this fixes https://bugzilla.xamarin.com/show_bug.cgi?id=58917
> ExTreeView: Don't try to explicitly render virtualized items

- Xwt.Gtk/Xwt.GtkBackend/BoxBackend.cs
- Xwt.Gtk/Xwt.GtkBackend/CanvasBackend.cs
When containers reallocate their children, a child might
request the container to re-reallocate. This leads to
a modificytion of the child collection during its enumeration,
resulting in an InvalidOperationException. Enumerating
the children to an array before reallocation solves
this rare case.
> [Gtk] Fix enumeration corruption on recursive size allocation

- Xwt.WPF/Xwt.WPFBackend/CustomScrollViewPort.cs
- Xwt.WPF/Xwt.WPFBackend/ScrollViewBackend.cs
When ScrollPolicy.Never is specified for a dimension, the ScrollView
should use the preferred size of the child to calculate its preferred
size for that dimension. This fixes the WPF backend to do that instead
of always measuring a zero size.
> [WPF] Fix layout for ScrollView with ScrollPolicy.Never

- Xwt.WPF/Xwt.WPFBackend/BoxBackend.cs
It is possible for IsArrangeValid to return true when
IsMeasureValid returns false. This is probably a bug
in WPF, but it is unfortunately what is happening.
This is a workaround for that issue. We should measure
when the measure is invalid :)
This fixes the case where the embedded exception dialog
or the loading spinner do not appear when opening a
storyboard file in Visual Studio.
> [WPF] Fix measuring for CustomPanel

- Xwt.WPF/Xwt.WPFBackend/CustomScrollViewPort.cs
If a larger child is replaced by a smaller one, we need to ensure the content offset
is re-clamped based on the new extents, otherwise the child may be scrolled entirely
out of the viewport.
> [WPF] CustomScrollViewPort: Ensure content offset is updated if child size changes

- Xwt.WPF/Xwt.WPFBackend/ExTreeView.cs
This fixes #740 
Just don't forget to fill up `shiftStart` when selected items are changed. Also, check for null.
> [WPF] Fixed an exception when selecting multiple TreeView items

- appveyor.yml
Automatic symbols deployment is broken due to a SSL/TLS error on AppVeyor.
> [AppVeyor] Disable symbols deployment

- Xwt.Gtk/Xwt.GtkBackend/ButtonBackend.cs
- Xwt.WPF/Xwt.WPFBackend/ButtonBackend.cs
- Xwt.XamMac/Xwt.Mac/ButtonBackend.cs
- Xwt/Xwt.Backends/IButtonBackend.cs
- Xwt/Xwt/Button.cs
This patch adds `Button.IsDefault` support. Depending on the toolkit, default buttons will be activated on special default actions inside a window (usually when the user presses the `Enter` key on the keyboard) and have a different design.
TODO: WPF support
> Add default button support

- Xwt.XamMac/Xwt.Mac/DialogBackend.cs
- Xwt.XamMac/Xwt.Mac/WindowBackend.cs
The original TransientFor impl. was just faking a dialog like behaviour by enforcing a window level and making a window float above all open window (including other apps). This patch makes use of the official Cocoa API to set and manage a window parent.
> [Mac] Fix Window.TransientFor

- Xwt.WPF/Xwt.WPFBackend/ExTreeView.cs
This fixes https://github.com/mono/xwt/issues/748
Removed malfunctioning call to `GetTreeItem()` method. It was calling `ItemContainerGenerator.ContainerFromItem()`, which for some reason returns null for any child item.
So while the root of the problem may lie somewhere deeper in the depths of WPF, these changes do fix the issue for us.
> [WPF] Fixed TreeView multiple child selection not working properly

- TestApps/Samples/Samples/TreeViews.cs
- Xwt.WPF/Xwt.WPFBackend/ExTreeViewItem.cs
- Xwt.WPF/Xwt.WPFBackend/WidgetBackend.cs
This closes #752
There are some merge conflicts with one of my other PRs, I'll fix the conflicts as soon as PRs are merged.
>  [WPF] Fixed drag operation starting even when mouse is outside TreeView

- Xwt.XamMac/Xwt.Mac/ListBoxBackend.cs
Remove deprecated column sizing code, since column sizing
is now handled by the base backend code (changed in #662)
(fixes #765)
> [Mac] Fix ListBox column autosizing

- Xwt.Gtk/Xwt.GtkBackend/GtkWorkarounds.cs
This matches these two functions to the C return types
> [Gtk] Use void instead of bool for pinvoke return types

- Xwt.XamMac/Xwt.Mac.CellViews/CanvasTableCell.cs
- Xwt.XamMac/Xwt.Mac.CellViews/CellUtil.cs
- Xwt.XamMac/Xwt.Mac.CellViews/CellViewBackend.cs
- Xwt.XamMac/Xwt.Mac.CellViews/CheckBoxTableCell.cs
- Xwt.XamMac/Xwt.Mac.CellViews/CompositeCell.cs
- Xwt.XamMac/Xwt.Mac.CellViews/ICellRenderer.cs
- Xwt.XamMac/Xwt.Mac.CellViews/ICellSource.cs
- Xwt.XamMac/Xwt.Mac.CellViews/ImageTableCell.cs
- Xwt.XamMac/Xwt.Mac.CellViews/RadioButtonTableCell.cs
- Xwt.XamMac/Xwt.Mac.CellViews/TextTableCell.cs
- Xwt.XamMac/Xwt.Mac/ListBoxBackend.cs
- Xwt.XamMac/Xwt.Mac/ListViewBackend.cs
- Xwt.XamMac/Xwt.Mac/Messaging.cs
- Xwt.XamMac/Xwt.Mac/NSTableViewBackend.cs
- Xwt.XamMac/Xwt.Mac/OutlineViewBackend.cs
- Xwt.XamMac/Xwt.Mac/TableViewBackend.cs
- Xwt.XamMac/Xwt.Mac/TreeViewBackend.cs
- Xwt.XamMac/Xwt.Mac/Util.cs
- Xwt/Xwt/ListStore.cs
This PR replaces the deprecated NSCell based table/cell implementation with the recommended NSView based table mode.
Features:
* Makes use of the native NSView caching technique (reusable cell views)
* Less allocations (only one backend instance for each CellView)
* Faster row/column size calculations
* Full CellView event support
> [Mac] NSView based tables

- TestApps/Samples/MainWindow.cs
- TestApps/Samples/Samples.csproj
- TestApps/Samples/Samples/TreeViewCustomStore.cs
- Testing/MacTestRunner.csproj
- Xwt.Gtk/Xwt.GtkBackend/CustomTreeModel.cs
- Xwt.Gtk/Xwt.GtkBackend/TreeStoreBackend.cs
- Xwt.Gtk/Xwt.GtkBackend/TreeViewBackend.cs
- Xwt/Xwt/DataField.cs
- Xwt/Xwt/ITreeDataSource.cs
- Xwt/Xwt/TreeStore.cs
The fix implements caching of indexes, to avoid scanning child lists every
time an index is required.
Fixed Gtk.TreeViewBacked, which didn't support custom TreePosition
implementations.
Added new sample.
> Fixed ITreeDataSource support in Gtk.TreeView

- Xwt.Gtk/Xwt.GtkBackend/CustomTreeModel.cs
- Xwt.Gtk/Xwt.GtkBackend/TreeViewBackend.cs
AppVeyor defaults to VS 2015 and fails to build C# 7. I've tried manually forcing it to use a VS 2017 image, but it has no Xamarin.Mac support. I think the easiest fix is to remove the C# 7 code.
> [AppVeyor] Fix build

- TestApps/Samples/Samples/TreeViewCustomStore.cs
- TestApps/Samples/Samples/TreeViews.cs
- Xwt.Gtk/Xwt.GtkBackend/TreeStoreBackend.cs
- Xwt.WPF/Xwt.WPFBackend/TreeStoreBackend.cs
- Xwt.XamMac/Xwt.Mac/TreeViewBackend.cs
- Xwt/Xwt/ITreeDataSource.cs
- Xwt/Xwt/TreeStore.cs
This allows the MAC NSOutlineView backend to handle `TreeStore.Clear()` properly. Right now ITreeDataSource does not notify at all when it's being cleared. Especially for large trees removing each note using the `NodeRemoved` event would be really slow, and a `Cleared` event might be useful in other cases too.
EDIT: Bug: NSOutlineView tried to render removed nodes, since it never noticed that the tree has been cleared.
>  Add ITreeDataSource.Cleared event 

- Xwt.Gtk/Xwt.GtkBackend/TableViewBackend.cs
The DragDrop fix introduced in 2107af1ab793598774cbae77afd44d76e2943a18
breaks cell editing by delaying row selection and reselecting a row on
the ButtonReleaseEvent stops the current editing operation immediatly.
To allow cell editing, we need to check whether multiple selection is enabled
and that already more than one row has been selected, before we do the
delayed selection.
Fixes VSTS #564512
> [Gtk] Fix editable cells

- Xwt.XamMac/Xwt.Mac/NSTableViewBackend.cs
- Xwt.XamMac/Xwt.Mac/OutlineViewBackend.cs
this improves the column autosizing by:
* skipping autosizing if there is only one expanded column
* code improvements
> [Mac] Improve column autosizing in tables

- Xwt.Gtk/Xwt.GtkBackend/TreeViewBackend.cs
- Xwt.WPF/Xwt.WPFBackend/TreeViewBackend.cs
- Xwt.XamMac/Xwt.Mac/OutlineViewBackend.cs
- Xwt.XamMac/Xwt.Mac/TreeViewBackend.cs
- Xwt/Xwt.Backends/ITreeViewBackend.cs
- Xwt/Xwt/TreeView.cs
The new property allows the client to enable/disable native TreeView animations.
For now only the Mac Backend supports this preference and is able to disable the row expand/collapse animations.
> Add TreeView.AnimationsEnabled

- TestApps/Gtk3Test/Gtk3Test.csproj
- TestApps/GtkOnMacTest/GtkOnMacTest.csproj
- TestApps/GtkOnWindowsTest/GtkOnWindowsTest.csproj
- TestApps/GtkTest/GtkTest.csproj
- TestApps/MixedGtkMacTest/MixedGtkMacTest.csproj
- TestApps/Samples/Samples.csproj
- TestApps/WpfTest/WpfTest.csproj
- TestApps/XamMacTest/XamMacTest.csproj
- Testing/CoreTests/CoreTests.csproj
- Testing/GtkTestRunner.csproj
- Testing/MacTestRunner.csproj
- Testing/WpfTestRunner.csproj
- Xwt.Gtk.Mac/Xwt.Gtk.Mac.csproj
- Xwt.Gtk.Windows/Xwt.Gtk.Windows.csproj
- Xwt.Gtk/Xwt.Gtk.csproj
- Xwt.Gtk/Xwt.Gtk3.csproj
- Xwt.WPF/Xwt.WPF.csproj
- Xwt.XamMac/Xwt.XamMac.csproj
- Xwt/Xwt.csproj
Use C# 6 to remain backwards compatible to old mono and avoid build failures on AppVeyor until we really need the new C# 7 language features.
> Set LangVersion to C# 6

- Xwt.WPF/Xwt.WPFBackend/TreeViewBackend.cs
The implementation of the `ScrollViewer` property calls `VisualTreeHelper.GetChild`, which throws if you call it before the WPF widget internal template has been realized:
```
System.ArgumentOutOfRangeException: Specified index is out of range or child at index is null. Do not call this method if VisualChildrenCount returns zero, indicating that the Visual has no children.
Parameter name: index
Actual value was 0.
Source=PresentationFramework
StackTrace:
at System.Windows.FrameworkElement.GetVisualChild(Int32 index) in f:\dd\wpf\src\Framework\System\Windows\FrameworkElement.cs:line 661
```
Setting `BorderThickness` on `Tree` fixes this and still has the desired effect.
> [WPF] Use Tree.BorderThickness instead of ScrollView.BorderThickness

- Xwt.XamMac/Xwt.Mac.CellViews/CheckBoxTableCell.cs
- Xwt.XamMac/Xwt.Mac.CellViews/CompositeCell.cs
- Xwt.XamMac/Xwt.Mac.CellViews/ImageTableCell.cs
- Xwt.XamMac/Xwt.Mac.CellViews/RadioButtonTableCell.cs
- Xwt.XamMac/Xwt.Mac/ListViewBackend.cs
- Xwt.XamMac/Xwt.Mac/OutlineViewBackend.cs
- Xwt.XamMac/Xwt.Mac/TreeViewBackend.cs
This patch reduces the amount of required recalculations while resizing rows and fixes row reallocation when the NSTableView is being resized.
> [Mac] Improve table row height calculation

- Xwt.XamMac/Xwt.Mac/TreeViewBackend.cs
- Xwt/Xwt/TreeStore.cs
All tree nodes are added to a list in the custom `NSOutlineViewDataSource`, but we never remove them. This patch makes sure that we correctly release deleted tree nodes, however this approach has a small perf issue: the tree backend will reload all children of a deleted node, until the node itself is removed. Reloading only expanded nodes reduces the impact.
* `DefaultTreeStoreBackend`: remove nodes recursively in reverse order and notify the tree backend of each removed node
* Release removed nodes
* Reload node children only if the node is expanded
> [Mac] Improve tree data source handling

- Xwt.XamMac/Xwt.Mac/TableViewBackend.cs
`NSTableView` has its own `BackgroundColor` property, use that instead of the generic layer based background coloring.
> [Mac] Fix ListView/TreeView background color

- Xwt.WPF/Xwt.WPFBackend/Util.cs
- Xwt.WPF/Xwt.WPFBackend/WidgetBackend.cs
This fixes two scenarios for the Android designer:
- When the designer is hosted in a _floating_ VS window,
GetParentWindow returns null.
- When the designer is hosted in the new XET tabbed editor control
GetParentWindow returns null (since it's actually a WinForms
component,   not WPF, that contains the designer)
In both cases, falling back to the WPF Application.Current.MainWindow
makes things work propertly.
>  Fallback to using the WPF MainWindow if can't get parent window

- Xwt.XamMac/Xwt.Mac/TreeViewBackend.cs
Try to measure visible cells for row height recalculation to avoid populating the template cell with data to measure the required cell size.
> [Mac] Improve CellView height recalculation

- TestApps/Samples/Samples/TreeViewEvents.cs
- Xwt.Gtk/Xwt.GtkBackend.CellViews/CustomCellRenderer.cs
- Xwt.XamMac/Xwt.Mac.CellViews/CanvasTableCell.cs
- Xwt.XamMac/Xwt.Mac.CellViews/CompositeCell.cs
- Xwt.XamMac/Xwt.Mac.CellViews/ICellRenderer.cs
- Xwt/Xwt.Backends/ICanvasCellViewFrontend.cs
- Xwt/Xwt/CanvasCellView.cs
This adds a new `CanvasCellView.GetRequiredSize (SizeConstraint widthConstraint)` func for size calculation and deprecates `CanvasCellView.GetRequiredSize ()`.
The `widthConstraint` will be set to the available width inside the column and row, or be unconstrained to calculate a default desired size.
TODO: WPF support (still uses deprecated calc without constraint).
> Constrained CanvasCellView sizing

- Xwt.Gtk/Xwt.GtkBackend/AccessibleBackend.cs
Found via https://github.com/mono/monodevelop/issues/4237
```
"/home/pi/sources/monodevelop/main/Main.sln" (default target) (1) ->
"/home/pi/sources/monodevelop/main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.csproj" (default target) (5) ->
"/home/pi/sources/monodevelop/main/external/xwt/Xwt.Gtk/Xwt.Gtk.csproj" (default target) (9:2) ->
Xwt.GtkBackend/AccessibleBackend.cs(138,17): error CS0219: Warning as Error: The variable `val' is assigned but its value is never used [/home/pi/sources/monodevelop/main/external/xwt/Xwt.Gtk/Xwt.Gtk.csproj]
```
> Remove warning in gtk accessibility code

- Xwt.Gtk.Mac/GtkMacAccessibleBackend.cs
- Xwt.Gtk/Xwt.GtkBackend/AccessibleBackend.cs
- Xwt.XamMac/Xwt.Mac/AccessibleBackend.cs
- Xwt/Xwt.Accessibility/Accessible.cs
- Xwt/Xwt.Accessibility/IAccessibleBackend.cs
Sometimes widgets have subregions that need their own accessible object. This
change allows native accessible objects to be added to Xwt.Accessible objects
as children
> [A11y] Allow native accessible children to be added to Xwt.Accessible

- TestApps/GtkOnWindowsTest/GtkOnWindowsTest.csproj
This fixes the build for linux where gtk# 3.0 is also installed on the system.
> Remove requires specific version for gtk

- Xwt.WPF/Xwt.WPFBackend/BoxBackend.cs
If we add something to the live tree it will have
an invalid measure and arrange. The first measure pass
will run as-expected.
If you remove and re-add the widget to the live tree
then it's measure and arrange will be invalidated, but
because we do not call 'ArrangeChildren (force = true)'
then we will never invoke the Measure for the children
again.
For the case of ListBox this means an implciit measure
will occur, which passes Inf,Inf as the size, which
means we lose scrollbars as it expands to fill all
that space.
This fixes the ExceptionPopover in the designers.
> [Wpf] Don't skip the Measure step all the time

- Xwt.WPF/Xwt.WPFBackend/DialogBackend.cs
Previously, the WPF ItemControls for dialog button groups, used to
lay out the buttons, were Focusable. That's apparently the
default for ItemControls (for reasons I don't fully understand, as it's
not normally for other WPF container controls).
Anyway, this caused the problem that when tabbing thru the dialog
controls you can set the focus not just to the buttons
themselves but also to the ItemsControl that contains them.
So tab navigation in the dialogs was somewhat broken, with two extra
stops for the two groups. Setting Focusable to false fixes that.
This fixes:
https://devdiv.visualstudio.com/DevDiv/Xamarin%20Android%20Designer/_workitems/edit/601178
https://devdiv.visualstudio.com/DevDiv/Xamarin%20Android%20Designer/_workitems/edit/601174 …
> Fix so dialog button group ItemsControls aren't Focusable

- Xwt.XamMac/Xwt.Mac/Util.cs
a NSView without a Window will cause `ConvertPointFromEvent` to throw a `NRE`, in this case is better just skip the BaseToScreen conversion.
> [Mac] Fixed `NRE` converting points from events.

- Xwt.Gtk/Xwt.GtkBackend/AccessibleBackend.cs
- Xwt.WPF/Xwt.WPF.csproj
- Xwt.WPF/Xwt.WPFBackend/AccessibleBackend.cs
- Xwt.WPF/Xwt.WPFBackend/BoxBackend.cs
- Xwt.WPF/Xwt.WPFBackend/CanvasBackend.cs
- Xwt.WPF/Xwt.WPFBackend/DropDownButton.cs
- Xwt.WPF/Xwt.WPFBackend/LabelBackend.cs
- Xwt.WPF/Xwt.WPFBackend/WidgetBackend.cs
- Xwt.WPF/Xwt.WPFBackend/WindowsSpinButton.xaml.cs
- Xwt.XamMac/Xwt.Mac/AccessibleBackend.cs
- Xwt/Xwt.Accessibility/Accessible.cs
- Xwt/Xwt.Accessibility/IAccessibleBackend.cs
- Xwt/Xwt/FrameBox.cs
- Xwt/Xwt/Widget.cs
This PR expands the accessibility support for the WPF backend in those ways:
- Add `LabeledBy` API to allow another widget to label this one
- Support the children accessibility API (for `Canvas` only as WPF doesn't allow to modify this information for existing widgets in general without subclassing and we mostly only care about supplying children accessibility object for custom-drawn and thus Canvas based elements anyway).
- Add a few more automation peers to some custom WPF controls we have
> [WPF] Accessibility support

- Xwt.WPF/Xwt.WPFBackend/BoxBackend.cs
This reverts commit cd022e582ada54440bee219cb38200946191fb64.
Context: http://work.devdiv.io/625851
The fix caused a regression in the Android designer where it seems to cause an infinite measure/layout pass for some users causing the CPU to go to 100% and make the whole system unusuable.
> Revert "[Wpf] Don't skip the Measure step all the time"

- Xwt.XamMac/Xwt.Mac/ImageHandler.cs
The NSCustomImageRep used for DrawingImage rendering
had always a zero size. However a modern macOS uses
the size to select the best matching image representation.
To ensure that our custom representation will be selected
for drawing, its size must match the NSImage size.
Fixes VSTS #648265
> [Mac] Fix DrawingImage rendering on macOS Mojave

- Xwt.Gtk/Xwt.GtkBackend.CellViews/CustomCellRendererImage.cs
- Xwt.Gtk/Xwt.GtkBackend.CellViews/CustomCellRendererText.cs
This change allows treeview/listview toggle cells to not be toggled,
unless the toggle button is clicked.
> [Gtk] Make CellRenderers activatable

- Xwt.XamMac/Xwt.Mac/MacSystemInformation.cs
- Xwt.XamMac/Xwt.Mac/PopupWindowBackend.cs
Previously there was no straightforward way to make an NSWindow transparent and hide the titlebar (unset `NSWindowStyle.Titled` style flag) without additional hacks. This has changed in Mojave in a way that unsetting the `NSWindowStyle.Titled` has the expected behaviour now (completely disables titlebar rendering).
> [Mac] Fix PopupWindow background rendering on Mojave

- Xwt.XamMac/Xwt.Mac/MacSystemInformation.cs
- Xwt.XamMac/Xwt.Mac/PopupWindowBackend.cs
backport #856 to `d15-9`
Previously there was no straightforward way to make an NSWindow transparent and hide the titlebar (unset NSWindowStyle.Titled style flag) without additional hacks. This has changed in Mojave in a way that unsetting the NSWindowStyle.Titled has the expected behaviour now (completely disables titlebar rendering).
> [d15-9][Mac] Fix PopupWindow background rendering on Mojave 

- Xwt.XamMac/Xwt.Mac/MacSystemInformation.cs
- Xwt.XamMac/Xwt.Mac/PopupWindowBackend.cs
backport #856 to `d15-8`
Previously there was no straightforward way to make an NSWindow transparent and hide the titlebar (unset NSWindowStyle.Titled style flag) without additional hacks. This has changed in Mojave in a way that unsetting the NSWindowStyle.Titled has the expected behaviour now (completely disables titlebar rendering).
> [d15-8][Mac] Fix PopupWindow background rendering on Mojave

- Xwt.Gtk/Xwt.GtkBackend.CellViews/CustomCellRendererText.cs
Setting CellRendererText.Editable to true would change the Mode
to Editable. However the code was then changing the Mode to
Activatable so the text cell could not be edited.
> [Gtk] Fix text cell not being editable

- Xwt.Gtk/Xwt.GtkBackend.CellViews/CustomCellRendererText.cs
Setting CellRendererText.Editable to true would change the Mode
to Editable. However the code was then changing the Mode to
Activatable so the text cell could not be edited.
> [7.7][Gtk] Fix text cell not being editable

- Xwt.WPF/Xwt.WPFBackend/ExTreeView.cs
- Xwt.WPF/Xwt.WPFBackend/ExTreeViewItem.cs
Repro steps:
* Open the sample app -> Widgets -> TreeView -> Remove selection
* Shift-Tab until you get to the TreeView
* Press ArrowUp key
* Crash (out of bounds)
> [WPF] Fixes a crash for ArrowUp into treeview without selected row

- Xwt.XamMac/Xwt.Mac/ImageBuilderBackendHandler.cs
- Xwt.XamMac/Xwt.Mac/ImageHandler.cs
Accessing the object's hashcode on a non-UI thread can cause problems
in native land
Fixes VSTS #731416 - VS for Mac crashes with "A fatal error has occurred" -  "System.NullReferenceException: at (wrapper managed-to-native) ObjCRuntime.Messaging.nuint_objc_msgSend(intptr,intptr)" at Xwt.Drawing.Image.Finalize () /external/xwt/Xwt/Xwt.Drawing/Image.cs:83
> [Mac] Dispose of images on the UI thread

- Xwt/Xwt.Backends/ResourceManager.cs
Since the underlying native value can change while the managed object
does not, we should use a non-virtual override for gethashcode here.
> ResourceManager should now use a stable hashcode

- TestApps/Samples/Samples/Labels.cs
- Testing/Tests/FormattedTextTests.cs
- Xwt.Gtk/Xwt.GtkBackend/GtkInterop.cs
- Xwt.XamMac/Xwt.Mac/TextLayoutBackendHandler.cs
- Xwt.XamMac/Xwt.Mac/Util.cs
- Xwt/Xwt.Drawing/FontSizeTextAttribute.cs
- Xwt/Xwt.csproj
- Xwt/Xwt/FormattedText.cs
This PR adds implementations  to cover "size" attribute in span tags in Gtk and Cocoa backends,
Example:
`<span size=\"10720\" font=\"Tahoma\" color='#0000ff'>blue</span>`
`<span size=\"xx-small\" font=\"Arial\" color='#ff0000'>red</span>`
`<span size=\"xx-large\" font=\"Tahoma\" color='#00ff00'>green</span>`
> Adds Size Attribute parsing in Span tags

- TestApps/Samples/Samples/Labels.cs
- Testing/Tests/FormattedTextTests.cs
- Xwt.Gtk/Xwt.GtkBackend/GtkInterop.cs
- Xwt.XamMac/Xwt.Mac/TextLayoutBackendHandler.cs
- Xwt.XamMac/Xwt.Mac/Util.cs
- Xwt/Xwt.Drawing/FontSizeTextAttribute.cs
- Xwt/Xwt.csproj
- Xwt/Xwt/FormattedText.cs
This PR adds implementations  to cover "size" attribute in span tags in Gtk and Cocoa backends,
Example:
`<span size=\"10720\" font=\"Tahoma\" color='#0000ff'>blue</span>`
`<span size=\"xx-small\" font=\"Arial\" color='#ff0000'>red</span>`
`<span size=\"xx-large\" font=\"Tahoma\" color='#00ff00'>green</span>`
> [d15-9] Adds Size Attribute parsing in Span tags 

- Xwt.Gtk/Xwt.GtkBackend/AccessibleBackend.cs
Setting Accessibility to `Xwt.ComboBoxEntry` doesn't work for `Gtk`, because `ComboBoxEntryBackend` uses `Gtk.Bin` as a container for entry ui element (https://github.com/mono/xwt/blob/master/Xwt.Gtk/Xwt.GtkBackend/ComboBoxEntryBackend.cs#L37).
So `Widget.Child` in this case is Entry element, which should be used as an a11y target.
> [Gtk][a11y] Support a11y for combobox entry

- Xwt.WPF/Xwt.WPFBackend/WindowFrameBackend.cs
I was trying to make an unstyled window movable via dragging the background and the window would move even when setting the location to itself, after some digging and trial & error I discovered GetBorderSize() would still return a size, even though there was none
This would cause the window to move by 3px in both x/y when setting the Location/calling Move
I'm not 100% sure this is the right way to fix it (you might want to change GetBorderSize?), but it certainly works and fixes the issue. I'll gladly change things around if anyone wants to suggest a better way
I've only tested it on Windows 10
> [WPF] Only take border size into account when decorated

- Xwt.Gtk/Xwt.GtkBackend/ComboBoxBackend.cs
in some situations i get a 
CallbackOnCollectedDelegate - Error for 
gtk-sharp!GtkSharp.TreeViewRowSeparatorFuncNative::Invoke
running xwt.gtk on windows (win7, win 10).
stack trace:
at Gtk.Application.gtk_main()
at Gtk.Application.Run()
at Xwt.GtkBackend.GtkEngine.RunApplication()
at Xwt.Application.<>c.<Run>b__21_0()
at Xwt.Toolkit.InvokePlatformCode(Action a)
at Xwt.Application.Run()
after this patch the error doesn't occur any more so far.
Info: Visual - Studio - Message (sorry, german):
Assistent für verwaltetes Debuggen "CallbackOnCollectedDelegate"    Nachricht = Assistent für verwaltetes Debuggen "CallbackOnCollectedDelegate" : "Für den von der Garbage Collection gesammelten Delegaten vom Typ "gtk-sharp!GtkSharp.TreeViewRowSeparatorFuncNative::Invoke" wurde ein Rückruf …
> Gtk.ComboBoxBackend: set Widget.RowSeparatorFunc to null on dispose

- Xwt.XamMac/Xwt.Mac/WindowBackend.cs
The fix introduced in 1af157a05698b084882519099e92a4f2b55d881c
is not required since Xamarin.Mac version 5.6 and has
the opposite effect.
Fixes VSTS #756962
> [Mac] Fix ref count bug when disposing windows

- Xwt/Xwt/Widget.cs
- Xwt/Xwt/XwtComponent.cs
This patch adds `XwtComponent.IsDisposed` and a check for the same when reallocating windows at the end of a UI loop.
> Check for disposed windows

- Xwt.XamMac/Xwt.Mac/BoxBackend.cs
If not, they participate in the key view loop, which makes focus being lost
on TAB navigation when there are boxes in the window.
> [Mac] Make boxes not take focus ever

- Xwt.Gtk/Xwt.GtkBackend/MenuBackend.cs
- Xwt.Gtk/Xwt.GtkBackend/WidgetBackend.cs
- Xwt.WPF/Xwt.WPFBackend/MenuBackend.cs
- Xwt.XamMac/Xwt.Mac/MenuBackend.cs
- Xwt/Xwt/Menu.cs
Allows menus to be shown relative to a target from a different toolkit. Only Cocoa above Gtk for now.
> Menu support for cross-toolkit targets

- Xwt.Gtk/Xwt.GtkBackend/BoxBackend.cs
We don't use HBox/VBox containers but let the frontend calculate
the widget allocation. This seems to confuse the Gtk focus order
calculation, especially if the widgets have additional alignemnt
requirements (vertical in HBox and horizontal in VBox).
Fixes VSTS #752833
> [Gtk] Fix the focus order of widgets inside a Box

- Directory.Build.targets
We have a Directory.Build.props so we should also add a .targets.
This is important because MSBuild searches upwards for both of
those files, so if we have a props and do not also have a targets
then it will be possible that we'll load up someone else's targets
*and not* also load up their props.
This affected the designer's build as Xwt skipped our props but took
our targets, and our targets depended on our props  :p
> [build] Add a Directory.Build.targets

- Xwt.XamMac/Xwt.Mac/DialogBackend.cs
This is required in the rare case when the runtime decides to resurrect a managed object and crashes if this constructor is missing. We have this already in WindowBackend and many others, DialogBackend was missing.
> [Mac] Add missing native ctor to dialog backend

- Xwt.Gtk/Xwt.GtkBackend/ComboBoxBackend.cs
Fixes:
```** (VisualStudio:96397): WARNING **: Gtk operations should be done on the main Thread
at System.Environment.get_StackTrace () [0x00000] in /Users/builder/jenkins/workspace/build-package-osx-mono/2018-08/external/bockbuild/builds/mono-x64/mcs/class/corlib/System/Environment.cs:316 
at Gtk.Application.AssertMainThread () [0x00023] in /Users/builder/jenkins/workspace/build-package-osx-mono/2018-08/external/bockbuild/builds/gtk-sharp-None/gtk/Application.cs:124 
at Gtk.ComboBox.set_RowSeparatorFunc (Gtk.TreeViewRowSeparatorFunc value) [0x00001] in /Users/builder/jenkins/workspace/build-package-osx-mono/2018-08/external/bockbuild/builds/gtk-sharp-None/gtk/generated/ComboBox.custom:66 
at Xwt.GtkBackend.ComboBoxBackend.Dispose (System.Boolean disposing) [0x00000] in …
```
> Fix crash when finalizing ComboBoxBackend

- Xwt.Gtk/Xwt.GtkBackend/RichTextViewBackend.cs
- Xwt.WPF/Xwt.WPFBackend/RichTextViewBackend.cs
- Xwt.XamMac/Xwt.Mac/RichTextViewBackend.cs
- Xwt/Xwt.Backends/IRichTextViewBackend.cs
- Xwt/Xwt/RichTextView.cs
These changes are mainly needed to fix Mac issue with the `MarkdownView` text color in Dark Mode. The default text color in Dark Mode is white. But it resets to black once formatted text is added to the`MarkdownView`. Exposing the `TextColor` property would give a chance to a client to solve the issue on its side.
Related vsts bug #`612427`.
Even though the PR's changes were initially made to fix a specific Mac's issue, I think this `RichTextView.TextColor` API could be useful in general.
Wpf's `TextColor` code was copied from `LabelBackend`, what is not nice. Let me know if I have a better option here.
> Add TextColor support to RichTextView component.

- Xwt/Xwt.Accessibility/Accessible.cs
- Xwt/Xwt.Accessibility/XwtAccessibleBackend.cs
- Xwt/Xwt.Backends/XwtWidgetBackend.cs
- Xwt/Xwt.csproj
- Xwt/Xwt/Widget.cs
This adds accessibility support to Xwt based default backends like `DefaultFileSelectorBackend`.
The XwtAccessibleBackend proxies accessibility from the xwt driven custom backend to the native backend of the content widget.
> Fix Xwt driven backend accessibility support

- Xwt.XamMac/Xwt.Mac/CanvasBackend.cs
- Xwt.XamMac/Xwt.Mac/LabelBackend.cs
- Xwt.XamMac/Xwt.Mac/LinkLabelBackend.cs
- Xwt.XamMac/Xwt.Mac/SpinButtonBackend.cs
By default internal alignment containers accept keyboard focus resulting in unexpected focus losses. This patch disables this behaviour (can be still enabled manually) and includes some additional minor accessibility fixes.
> [Mac] Fix container focus being enabled by default

- Xwt.XamMac/Xwt.Mac/RichTextViewBackend.cs
- Xwt.XamMac/Xwt.Mac/Util.cs
Setting the text color to its previous value after applying
an attributed string. Otherwise the text color resets to Black
no matter of what color it was before.
VSTS Bug: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/612427
> [XamMac] Fix NSTextView text color bug.

- Xwt.XamMac/Xwt.Mac/RichTextViewBackend.cs
- Xwt.XamMac/Xwt.Mac/Util.cs
Fix the text color only if the initially applying formatted text
doesn't contain any ForegroundColor attributes.
Previous approach didn't work, because converting html attributes using
`initWithHTML:documentAttributes:` added default text color attribute
to each html attribute.
So `MacRichTextBuffer.CreateStringFromHTML` ended up building
an attributed string containing many ForegroundColor attributes.
> [XamMac] Updates https://github.com/mono/xwt/pull/925

- Xwt/Xwt.Backends/BackendHost.cs
- Xwt/Xwt/Paned.cs
- Xwt/Xwt/Toolkit.cs
- Xwt/Xwt/WindowFrame.cs
- Xwt/Xwt/XwtComponent.cs
This reverts commit 98e0110a073950aada926a68e1ca96ad843a3fff.
This is here so I don't forget to work on the patch.
```
** (MonoDevelop:702): WARNING **: Gtk operations should be done on the main Thread
at System.Environment.get_StackTrace () [0x00000] in /Users/builder/jenkins/workspace/build-package-osx-mono-pullrequest/pr/external/bockbuild/builds/mono-x64/mcs/class/corlib/System/Environment.cs:316 
at Gtk.Application.AssertMainThread () [0x00023] in /Users/builder/jenkins/workspace/build-package-osx-mono-pullrequest/pr/external/bockbuild/builds/gtk-sharp-None/gtk/Application.cs:124 
at Gtk.Widget.set_Events (Gdk.EventMask value) [0x00001] in /Users/builder/jenkins/workspace/build-package-osx-mono-pullrequest/pr/external/bockbuild/builds/gtk-sharp-None/gtk/generated/Widget.cs:97 
at …
```
> Fix leaks coming in from event subscription

- Xwt.XamMac/Xwt.Mac/WindowFrameBackend.cs
When wrapping an NSWindow with an existing delegate, we
should not subscribe to any managed events and trigger
the default delegate creation.
Fixes VSTS #831134
> [Mac] Avoid touching the Delegate of a wrapped window

- Xwt.XamMac/Xwt.Mac/WindowFrameBackend.cs
When wrapping an NSWindow with an existing delegate, we
should not subscribe to any managed events and trigger
the default delegate creation.
Fixes VSTS #831134
(cherry picked from commit db0ed4f97632480c0d1c63568595fabe08729aab)
Backport of #929
> [d16-0][Mac] Avoid touching the Delegate of a wrapped window

- Xwt.Gtk/Xwt.GtkBackend/ImageHandler.cs
This is a quick workaround for the case when a multisize
image is created from a set of custom drawn images.
GtkImage does not support combinations of custom drawing
and bitmap frames for the same image. In that case the
custom drawn multisize image is selected.
> [Gtk] Always take the custom drawn image for Multisize

- Xwt/Xwt/Box.cs
A couple of overloads for `PackEnd` are broken, because they pass `PackOrigin.End` to the `Pack` but the value is never used.
> FIxed `Pack` to use `PackOrigin` parameter instead `PackOrigin.Start`.

- Xwt.XamMac/Xwt.Mac/PopoverBackend.cs
* There is is a bug on AppKit where if you don't set the `Appearance` for you view, the `NSTextField` will be displayed with gray background
https://stackoverflow.com/questions/29074724/how-to-change-nstextfield-background-color-in-nspopover
> [Mac] Fixed bug with Popover where the TextEntry is gray.

- Xwt.XamMac/Xwt.Mac/PopoverBackend.cs
NSAppearanceNameDarkAqua is not available before Mojave.
This also fixes the build on systems with an older Xamarin.Mac
version (incl. our own CI)
Regressed in #941
> [Mac] Popover appearance on High Sierra and older

- Xwt.XamMac/Xwt.Mac/AlertDialogBackend.cs
- Xwt.XamMac/Xwt.Mac/WindowBackend.cs
This is a hack, macOS seems to be calling conformsToProtocol:
after a window has been released, resulting in a crash.
Fixes VSTS #935146
> [Mac] Fix ObjectDisposedException with TouchBar

- Xwt.XamMac/Xwt.Mac/WindowBackend.cs
Since the y-axis is inverted on Mac, we need to recalculate
the Y position to keep the window in place when it's being
resized vertically.
> [Mac] Preserve the window location when resizing vertically

- Xwt.Gtk/Xwt.GtkBackend/DialogBackend.cs
https://github.com/mono/xwt/blob/master/Xwt.XamMac/Xwt.Mac/DialogBackend.cs#L181
https://github.com/mono/xwt/blob/master/Xwt.WPF/Xwt.WPFBackend/DialogBackend.cs#L166
> [GTK] Close dialog on EndLoop to be consistent with XamMac and WPF

- Xwt.XamMac/Xwt.Mac/AlertDialogBackend.cs
- Xwt.XamMac/Xwt.Mac/WindowBackend.cs
This is a hack, macOS seems to be calling conformsToProtocol:
after a window has been released, resulting in a crash.
Fixes VSTS #935146
Backport of #952
> [d16-2] [8.2] [Mac] Fix ObjectDisposedException with TouchBar

- Xwt.XamMac/Xwt.Mac/PopoverBackend.cs
The `NativeChild.EffectiveAppearance` is `Aqua` in most cases since the NativeChild was just created. Use the EffectiveAppearance from the reference view instead.
> [Mac] Fix Popover appearance on Mac.

- Xwt.WPF/Xwt.WPFBackend/AlertDialogBackend.cs
The result of working WPF backend was wrong and looked bad. I changed it to use Text as Title and SecondaryText as a base message of resulting dialog.
The system message box as backend:
The custom dialog as backend:
> [Windows] Fix AlertDialogBackend on Windows

- Xwt.XamMac/Xwt.Mac/ViewBackend.cs
NSControl is not meant to be used as a container and has special restrictive a11y behavior. Using a simple NSView as a layout container makes its content magically accessible.
Simple repro steps: Add a margin to the table inside the dialog example and enable VO: https://github.com/mono/xwt/blob/master/TestApps/Samples/Samples/Windows.cs#L61
Fixes VSTS #965764
> [Mac] Don't use NSControl to layout margins

- Xwt.WPF/Xwt.WPFBackend/AlertDialogBackend.cs
- Xwt/Xwt/MessageDialog.cs
The result of working WPF backend was wrong and looked bad. I added more
methods with parameter Title for MessageDialog and implemented using of
it for WPF backend.
Also, I added the setting Title by using parent window info for WPF
backend.
See screenshots at #961 
Sample of using Title from the parent window, if it wasn't set for MessageDilog:
Sample with the generic title:
> [Windows] Add support of Title for AlertDialogBackend on Windows

- Xwt.XamMac/Xwt.Mac/AlertDialogBackend.cs
- Xwt.XamMac/Xwt.Mac/WindowBackend.cs
This is a hack, macOS seems to be calling conformsToProtocol:
after a window has been released, resulting in a crash.
Fixes VSTS #935146
(cherry picked from commit 41f29ad6848b07e64d8da9699118613e668d44bf)
Backport of #952
> [d16.3] [Mac] Fix ObjectDisposedException with TouchBar

- Xwt.Gtk.Mac/Carbon.cs
- Xwt.Gtk.Mac/GtkMacDesktopBackend.cs
```
WARNING: The Gestalt selector gestaltSystemVersion is returning 10.9.5 instead of 10.14.5. This is not a bug in Gestalt -- it is a documented limitation. Use NSProcessInfo's operatingSystemVersion property to get correct system version number.
```
Fixes https://github.com/mono/monodevelop/issues/7745
> [Mac] Replace a PInvoke which logs an error at runtime

- Xwt.XamMac/Xwt.Mac/PopoverBackend.cs
If the popover has already been closed, it's delegate
might have been released, so that accessing it would cause
unsupported NSObject resurrection.
Fixes VSTS #803040
> [Mac] Fix Popover backend disposing

- Xwt.Gtk/Xwt.GtkBackend/LabelBackend.cs
- Xwt.Gtk/Xwt.GtkBackend/Util.cs
This broke with https://github.com/mono/xwt/commit/2102683398a84ee16094fc4bcae3dac44ba31872#diff-b2fc874d943bfbde146e59ed3a809b6f
which removed the assignment for TextIndexer, so trying to access it,
now that it is never assigned, results in a NRE.
> [Gtk] Fix NRE on LabelBackend's TextIndexer

- Xwt/Xwt.Drawing/Image.cs
A ThemedImage consists of a set of Images with different tags
and the single child images can have several resolutions loaded
from different files.
When switching between toolkits, NativeImageRef.LoadForToolkit
reloads the images for the new toolkit based on NativeImageSource
which holds all data sufficient to reconstruct a ThemedImage.
When performing the actual loading using Image.LoadImage,
several issues occurred:
* NativeImageRef.LoadForToolkit did not pass the tags specified
for the given source when loading images directly from resources
or files
* Image.LoadImage always added the base image file even if
the tag filter did not match. This resulted in creation
of another nested ThemedImage (with an image group for the specified
tag and the untagged base image), instead of a simple …
> Fix tag filtering when reloading tagged images

- Xwt.XamMac/Xwt.Mac/PopoverBackend.cs
> [Mac] Fix crash due to a missing IntPtr ctor in NSAppearanceCustomizationPopover

- Xwt/Xwt.Drawing/ComposedImage.cs
- Xwt/Xwt.Drawing/Image.cs
The new ComposedImage type renders several Images as one.
The only way to create composed images is to use `ImageBuilder` to draw several images to a `VectorImage`, like we do in MonoDevelop: https://github.com/mono/monodevelop/blob/11bd01f8a6260e0ef9c9f5fb6b7fbc7a0e47c191/main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/ImageService.cs#L579-L603
Unfortunately, the ImageBuilder (and so VectorImage) is not cross-tookit capable, because it uses the native [`ContextBackendHandler`](https://github.com/mono/xwt/blob/master/Xwt/Xwt.Backends/ContextBackendHandler.cs#L64) API, by recording native rendering steps (`ImageDescription` for images). This means that a new ImageBuilder needs to be created in the context of each toolkit being used separately.
ComposedImage adds a simple way to workaround …
> Add support for composed images

- Xwt.Gtk/Xwt.GtkBackend/MenuItemBackend.cs
The MenuItemBackend calls Destroy on a Gtk object it did not create.
> Remove call to label.Destroy()

- Xwt.XamMac/Xwt.Mac/ImageHandler.cs
Fixes VSTS #997904
Backport of #979
(cherry picked from commit e8aee72de5d07d062f70021c7ccdb334cb360596)
> [16.3][Mac] Fix NRE in CustomImage

- Xwt.Gtk/Xwt.GtkBackend.CellViews/CellViewBackend.cs
- Xwt.Gtk/Xwt.GtkBackend.CellViews/Gtk2CellRendererCustom.cs
- Xwt.Gtk/Xwt.GtkBackend.CellViews/Gtk3CellRendererCustom.cs
Backport of #985
(cherry picked from commit 677f3ebe27f9241daf38b2191c60a2f47b278ef6)
> [16.4][Gtk] Add AccessibleFields.Label support to custom cell renderers

- TestApps/Samples/Samples/ProgressBarSample.cs
- TestApps/WpfTest/Directory.Build.targets
- TestApps/WpfTest/WpfTest.csproj
- TestApps/WpfTest/app.config
- Xwt.Gtk.Mac/GtkMacAccessibleBackend.AccessibilityHelper.cs
- Xwt.Gtk.Mac/GtkMacAccessibleBackend.cs
- Xwt.Gtk.Mac/Xwt.Gtk.Mac.csproj
- Xwt.Gtk/Xwt.GtkBackend/AccessibleBackend.cs
- Xwt.WPF/Directory.Build.props
- Xwt.WPF/Xwt.WPF.csproj
- Xwt.WPF/Xwt.WPFBackend/AccessibleBackend.AccessibilityHelper.cs
- Xwt.WPF/Xwt.WPFBackend/AccessibleBackend.cs
- Xwt.WPF/Xwt.WPFBackend/WPFEngine.cs
- Xwt.XamMac/Xwt.Mac/AccerssibilityHelper.cs
- Xwt.XamMac/Xwt.Mac/AccessibleBackend.AccessibilityHelper.cs
- Xwt.XamMac/Xwt.Mac/AccessibleBackend.cs
- Xwt.XamMac/Xwt.XamMac.csproj
- Xwt/Xwt.Accessibility/Accessible.cs
- Xwt/Xwt.Accessibility/IAccessibleBackend.cs
- Xwt/Xwt.Accessibility/XwtAccessibleBackend.cs
* Allows to check whether accessibility means are in use (Narrator/3rd party tools on Windows, VoiceOver on macOS)
* Adds `Accessible.MakeAnnouncement (string message, bool polite = false)` method for making a custom announcement for user per request (uses LiveRegion on Windows and `NSAccessibility.PostNotification` on macOS)
WPF version requires target framework version .NET 4.7.2
> [WPF][XamMac][GtkMac] A11y helper

- TestApps/Samples/Samples/ProgressBarSample.cs
- TestApps/WpfTest/Directory.Build.targets
- TestApps/WpfTest/WpfTest.csproj
- TestApps/WpfTest/app.config
- Xwt.Gtk.Mac/GtkMacAccessibleBackend.AccessibilityHelper.cs
- Xwt.Gtk.Mac/GtkMacAccessibleBackend.cs
- Xwt.Gtk.Mac/Xwt.Gtk.Mac.csproj
- Xwt.Gtk/Xwt.GtkBackend/AccessibleBackend.cs
- Xwt.WPF/Directory.Build.props
- Xwt.WPF/Xwt.WPF.csproj
- Xwt.WPF/Xwt.WPFBackend/AccessibleBackend.AccessibilityHelper.cs
- Xwt.WPF/Xwt.WPFBackend/AccessibleBackend.cs
- Xwt.WPF/Xwt.WPFBackend/WPFEngine.cs
- Xwt.XamMac/Xwt.Mac/AccerssibilityHelper.cs
- Xwt.XamMac/Xwt.Mac/AccessibleBackend.AccessibilityHelper.cs
- Xwt.XamMac/Xwt.Mac/AccessibleBackend.cs
- Xwt.XamMac/Xwt.XamMac.csproj
- Xwt/Xwt.Accessibility/Accessible.cs
- Xwt/Xwt.Accessibility/IAccessibleBackend.cs
- Xwt/Xwt.Accessibility/XwtAccessibleBackend.cs
* Allows to check whether accessibility means are in use (Narrator/3rd party tools on Windows, VoiceOver on macOS)
* Adds Accessible.MakeAnnouncement (string message, bool polite = false) method for making a custom announcement for user per request (uses LiveRegion on Windows and NSAccessibility.PostNotification on macOS)
WPF version requires target framework version .NET 4.7.2
(cherry picked from commit 0893ad38d87373d65320f47c458d8bd46858ae0c)
Backport of #935
> [16.4][WPF][XamMac][GtkMac] A11y helper

- Xwt.Gtk/Xwt.GtkBackend/AccessibleBackend.cs
This fix is not required with latest AtkCocoa
This reverts commit 2abba7b56283ec27cd1632b5e4f10dd1dfc56ae1 (part of #875).
> Revert "[Gtk][a11y] Use toggle button in comboboxes for setting a11y."

- Xwt.Gtk/Xwt.GtkBackend/AccessibleBackend.cs
This fix is not required with latest AtkCocoa
This reverts commit 2abba7b (part of #875).
(cherry picked from commit a1c22f197e67160372a1093f0b28f273d88e3e05)
Backport of #987
> [16.4] Revert "[Gtk][a11y] Use toggle button in comboboxes for setting a11y."

- Xwt.Gtk/Xwt.GtkBackend/PopoverBackend.cs
- Xwt.WPF/Xwt.WPFBackend/AccessibleBackend.cs
- Xwt.WPF/Xwt.WPFBackend/MenuBackend.cs
This PR contains two a11y fixes:
1. The Esc key now closes Gtk based popovers
2. Previously, setting a11y info (like the name) on a popup menu didn't work for WPF. This is now supported. Since the menu is actually created when it's first displayed, the a11y settings are remembered in the AccessibilityBackend members and then copied to the menu when first created, similar to how we already handle this for Popovers.
> [Gtk][WPF] A11y fixes for menus and popovers

- Xwt.Gtk/Xwt.GtkBackend/PopoverBackend.cs
- Xwt.WPF/Xwt.WPFBackend/AccessibleBackend.cs
- Xwt.WPF/Xwt.WPFBackend/MenuBackend.cs
This is backport of https://github.com/mono/xwt/pull/992.
It contains two a11y fixes:
The Esc key now closes Gtk based popovers
Previously, setting a11y info (like the name) on a popup menu didn't work for WPF. This is now supported. Since the menu is actually created when it's first displayed, the a11y settings are remembered in the AccessibilityBackend members and then copied to the menu when first created, similar to how we already handle this for Popovers.
> [d16-4][Gtk][WPF] A11y fixes for menus and popovers

- Xwt.Gtk/Xwt.GtkBackend/Util.cs
Using markup to define a hyperlink in a label was not highlighting
the hyperlink with blue text and the underline. The problem was that
the FastPangoAttrList was not being applied to the label.
> Fix hyperlinks not highlighted in labels

- Xwt.Gtk/Xwt.GtkBackend/AccessibleBackend.cs
(cherry picked from commit 65b5b2bbacf7103b153c189383063a5f16afc87c)
Backport of #1002
> [Gtk] Fix TableViewBackend accessibility support

- Xwt.WPF/Xwt.WPFBackend/AccessibleBackend.AccessibilityHelper.cs
SPI_GETSCREENREADER sometimes returns true when Narrator is Off
ListenerExists checks should be sufficient - tested on Windows 10 1903 and Windows 7 7601 SP 1 with system narrator, NVDA and JAWS (on Win 10).
Related issue: https://github.com/microsoft/vscode/issues/27893
> [A11Y][WPF] Avoid false-positive SPI_GETSCREENREADER

- Xwt.XamMac/Xwt.Mac/MacEngine.cs
- Xwt.XamMac/Xwt.Mac/NSApplicationInitializer.cs
1. Clean up `NSApplicationInitializer`:
1. by using `[ThreadStatic]` which is 2-3x faster than `Thread. GetNamedDataSlot` etc
2. stop using reflection to set `IgnoreMissingAssembliesDuringRegistration` (I think we're far enough into the future to stop paying for this reflection cost on every startup).
2. Support instantiating custom subclasses of XWT's `AppDelegate` so other standard macOS app delegate methods can be handled by the application using XWT. This is necessary, for example, to support OSA scripting.
> MacEngine: support custom NSApplicationDelegate, improve init

- Xwt.XamMac/Xwt.Mac/NSApplicationInitializer.cs
This allowed NSApplication.Init () to be called several times
from different threads, causing random "System.InvalidOperationException:
Init has already been invoked; it can only be invoked once" exceptions.
Partially reverts 36b5c71a817b6e9c7874f2c0c2de5509c3db2cd0
> [Mac] Remove ThreadStatic from NSApplicationInitializer.initialized

- Xwt.XamMac/Xwt.Mac/DialogBackend.cs
- Xwt.XamMac/Xwt.Mac/WindowBackend.cs
Sometimes VO does not follow the current active window.
Manually checking and setting AccessibilityFocusedWindow
sometimes fixes this issue.
> [Mac] Fix AccessibilityFocusedWindow when parenting windows

- Xwt.XamMac/Xwt.Mac/DialogBackend.cs
- Xwt.XamMac/Xwt.Mac/WindowBackend.cs
Sometimes VO does not follow the current active window.
Manually checking and setting AccessibilityFocusedWindow
sometimes fixes this issue.
(cherry picked from commit 4b347bc96a7c6a329053d4a36878faa188f34282)
> [16.4][Mac] Fix AccessibilityFocusedWindow when parenting windows

- Xwt.XamMac/Xwt.Mac/MacEngine.cs
Keep track of the startup reason so applications can access it
Fixes VSTS #984249
> [MacEngine] Track the startup reason

- Xwt.XamMac/Xwt.Mac/MacEngine.cs
Keep track of the startup reason so applications can access it
Fixes VSTS #984249
(cherry picked from commit eb69ad4222ae47b9e5a64923c39932c0838604bf)
Backport of #1016
> [16.4][MacEngine] Track the startup reason

- Xwt/Xwt.Drawing/Context.cs
- Xwt/Xwt.Drawing/ThemedImage.cs
GetImage is optimized for performace and therefore just loops over
the images and selects the first best matching one based on given styles.
The result is not predictable if the image list is not sorted and several alternatives
match different global and explicit styles.
Since we want to prioritize explicit styles first, we need to make sure that we
don't select an image with a given global style but without an explicit match first.
The simplest approach without slowing down rendering by a sophisticated lookup is to
sort images matching global styles last, so that GetImage would always select
an alternative with an explicit rather than a global style.
**[High contrast Mode](https://github.com/mono/monodevelop/pull/9510) Example from MonoDevelop**
We use two problematic/conflicting styles: …
> Make ThemedImage style selection less unpredictable

- Xwt/Xwt.Drawing/Context.cs
- Xwt/Xwt.Drawing/ThemedImage.cs
GetImage is optimized for performace and therefore just loops over
the images and selects the first best matching one based on given styles.
The result is not predictable if the image list is not sorted and several alternatives
match different global and explicit styles.
Since we want to prioritize explicit styles first, we need to make sure that we
don't select an image with a given global style but without an explicit match first.
The simplest approach without slowing down rendering by a sophisticated lookup is to
sort images matching global styles last, so that GetImage would always select
an alternative with an explicit rather than a global style.
(cherry picked from commit 11fc060e02b6c0c2e3ad24c203247aaab0a4e943)
Backport of #1021
> [16.4] Make ThemedImage style selection less unpredictable

- Directory.Build.props
- Directory.Build.targets
- Xwt.Gtk.Mac/Xwt.Gtk.Mac.csproj
- Xwt.Gtk.Windows/Xwt.Gtk.Windows.csproj
- Xwt.Gtk/Xwt.Gtk.csproj
- Xwt.Gtk/Xwt.Gtk3.csproj
- Xwt.WPF/Directory.Build.props
- Xwt.WPF/Xwt.WPF.csproj
- Xwt.WPF/Xwt.WPFBackend/AccessibleBackend.AccessibilityHelper.cs
- Xwt.XamMac/Xwt.XamMac.csproj
- Xwt/Directory.Build.props
- Xwt/Xwt.Design/DesignerSurface.cs
- Xwt/Xwt.Drawing/Color.cs
- Xwt/Xwt.Drawing/Font.cs
- Xwt/Xwt.csproj
- Xwt/Xwt/Box.cs
- Xwt/Xwt/Canvas.cs
- Xwt/Xwt/CheckBox.cs
- Xwt/Xwt/CursorType.cs
- Xwt/Xwt/Expander.cs
- Xwt/Xwt/Frame.cs
- Xwt/Xwt/FrameBox.cs
- Xwt/Xwt/Notebook.cs
- Xwt/Xwt/Paned.cs
- Xwt/Xwt/RadioButton.cs
- Xwt/Xwt/Size.cs
- Xwt/Xwt/Table.cs
- Xwt/Xwt/Widget.cs
- Xwt/Xwt/WidgetSpacing.cs
This removes System.Xaml reference which was only used to serialize/deserialize xaml.
Port Xwt to ns2.0, and platform assemblies to net472.
> Port Xwt to netstandard2.0

- Xwt.XamMac/Xwt.Mac/AccessibleBackend.cs
Accessible should operate on the actual table and not its parent scroll view.
> [Mac] Fix Table Accessible support

- Xwt.XamMac/Xwt.Mac/AccessibleBackend.cs
Accessible should operate on the actual table and not
its parent scroll view.
Backport of #1024
> [16.4] [Mac] Fix Table Accessible support

- Xwt.XamMac/Xwt.Mac/AccessibleBackend.cs
Accessible should operate on the actual table and not
its parent scroll view.
Backport of #1024
> [16.5] [Mac] Fix Table Accessible support

- Xwt.Gtk/Xwt.GtkBackend/PopoverBackend.cs
In order to test replace
```
void PopoverHidden (object sender, EventArgs e)
{
sink.OnClosed ();
popover.Hidden -= PopoverHidden;
}
```
with
```
void PopoverHidden (object sender, EventArgs e)
{
Console.WriteLine ("Backend  Popover_Hidden event");
sink.OnClosed ();
//popover.Hidden -= PopoverHidden;
}
```
then open Sample -> Popover page and open and close a button to trigger Popover, observe how console accumulates the messages with each Show
> [GTK] Unsubscribe Popover from Hidden event on hiding

- Xwt.XamMac/Xwt.Mac.CellViews/CellViewBackend.cs
This is required for proper a11y contrast support when the window has no focus.
> [Mac] Add CellView.IsHighlighted support

- Xwt.XamMac/Xwt.Mac.CellViews/CellViewBackend.cs
This is required for proper a11y contrast support when the window has no focus.
Backport of https://github.com/mono/xwt/pull/1042
> [16.7][Mac] Add CellView.IsHighlighted support

- Xwt.Gtk.Mac/MacPlatformBackend.cs
- Xwt.Gtk/Xwt.GtkBackend/GtkEngine.cs
- Xwt.Gtk/Xwt.GtkBackend/GtkPlatformBackend.cs
- Xwt.Gtk/Xwt.GtkBackend/WidgetBackend.cs
This replaces Gtk tooltips with native ones. When Widget.TooltipText is set, a new native tooltip area is being added to the native NSView of the the Gtk.Widget, which gets updated automatically on text or allocation changes.
> [Gtk][Mac] Add native tooltip support on macOS

- Xwt/Xwt.Drawing/Image.cs
With embedded resources:
gtc-solution.png
gtc-solution@2x.png
gtc-solution~contrast.png
gtc-solution-filter.png
gtc-solution-filter@2x.png
gtc-solution-filter~contrast.png
The ParseImageHints method would find an image match when the
baseName was gtc-solution and the fileName was gtc-solution@2x.png
or gtc-solution~contrast.png. The problem was the original check
used fileName.StartsWith(baseName) which allowed this mismatch.
Changing the check to compare the fileName before the first
delimiter found with the baseName avoids an incorrect image being
used.
> Fix incorrect alternative images being used

- Xwt.XamMac/Xwt.Mac/ComboBoxBackend.cs
When the NSPopUpButton.SelectItem(nint index) is called the
ComboBox.SelectionChanged event is now fired. This allows UI automation
tools to select the combo box item programatically and still allow the
XWT SelectionChanged event to be triggered.
> [Mac] Fire ComboBox.SelectionChanged when item selected in code

- Xwt.XamMac/Xwt.Mac/NSApplicationInitializer.cs
This patch allows for two main improvements:
* The entry assembly and its dependencies are no longer force-loaded
* We register assemblies that are not referenced by the entry assembly
and are loaded later on by the app
> [Mac] Manually register assemblies for Xamarin.Mac

- Xwt.XamMac/Xwt.Mac/MacEngine.cs
- Xwt/Xwt.Backends/ToolkitEngineBackend.cs
- Xwt/Xwt/Application.cs
- Xwt/Xwt/Toolkit.cs
If Xwt.Mac is initialized inside a Cocoa application then
NSApplication.Initialize cannot be called twice.
> Allow application to specify whether to initialize parent toolkit or not

- Xwt.XamMac/Xwt.Mac/MacEngine.cs
- Xwt/Xwt.Backends/ToolkitEngineBackend.cs
- Xwt/Xwt/Application.cs
NSApplication.Main never returns. The only way to return an exit code is to call exit(code).
> Allow specifying an exit code when exiting the application

- Xwt/Xwt/Application.cs
When used as a guest toolkit, there needs to be a call to ExitUserCode or non
of the dispatch code works
> [Xwt] Exit user code when initialising as guest

- Xwt.XamMac/Xwt.Mac/NSApplicationInitializer.cs
Reflection-only assemblies do not support having code executed, and
dependencies cannot be resolved by the dynamic registrar without the
AppDomain.ReflectionOnlyAssemblyResolve being used to resolve the
assemblies.
> [Mac] Do not register reflection-only assemblies with registrar.

- Xwt.XamMac/Xwt.Mac/TableViewBackend.cs
This removes the Big Sur check from #1060, since the trigger for this issue is not Big Sur but building with Xcode 12.
> [Mac] Fix TableView selection rendering when building with Xcode 12

- Xwt.XamMac/Xwt.Mac/ImageHandler.cs
Cocoa sometimes creates a copy of an NSImage to cache it,
in that case we also need to copy all custom image properties
and settings.
> Copy image properties when copying CustomImage

- Xwt.XamMac/Xwt.Mac/KeyboardUtil.cs
Switch to using Characters instead of CharactersIgnoringModifiers as Cocoa passes the Roman key in Characters when used with a modifier so that commands like
cmd+v still work correctly
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1454138
> [Xwt.Mac] Handle non-roman keyboard layouts correctly

- Xwt.XamMac/Xwt.Mac/ImageHandler.cs
Also optimize a multiple IEnumerable enumeration path and switch to NSImage.FromStream.
> Optimize some image API usages

- Xwt.XamMac/Xwt.Mac/LinkLabelBackend.cs
- Xwt.XamMac/Xwt.Mac/MacDesktopBackend.cs
Update XamMac link labels to launch the browser directly,
in the standard way we do it elsewhere in VSMac.
Fixes  https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1484767
This behavior worked before with the Gtk backend, but
I don't think it ever worked properly with the Cocoa
> Fix Cocoa link labels to properly launch the browser

- Xwt.XamMac/Xwt.Mac/DialogBackend.cs
- Xwt.XamMac/Xwt.Mac/Util.cs
This PR fixes set the correct parent when a dialog is shown in modal in the CocoaBackend and it also ensures it's centered to it.
> [Xam.Mac] Fixes parenting in DialogBackend

- Xwt.XamMac/Xwt.Mac/PasswordEntryBackend.cs
This PR fixes the following issues with the VSM add apple developer account dialog:
-autofill password does not enable the sign in button because the password from Apple Keychain is not being detected by the change handler
-long passwords wrap onto multiple lines
> Fix password autofill and wrapping

- Xwt.XamMac/Xwt.Mac/AlertDialogBackend.cs
In cocoa backend when opening an modal AlertBox we need specify a parent and center to it for a correct positioning and avoid odd behaviours.
> [AlertDialogBackend] Ensures parent is set using the active window if there are not any window specified 

- Xwt.XamMac/Xwt.Mac/DialogBackend.cs
Ensures our new modal dialog is going to use the current focused window as a parent in case of null
> Sets a default parent in dialogs with empty parent

- Xwt.XamMac/Xwt.Mac/ViewBackend.cs
Fix so that drag/drop support works properly with the Cocoa backend.
This PR includes these fixes:
1. DraggingUpdate passed the wrong coordinates. Now do the proper conversion from view coordinates to window coordinates, as expected by the Xwt client.
2. Get the INSDraggingInfo object in the proper way, with `Runtime.GetINativeObject<INSDraggingInfo> (dragInfo, owns: false)`, same as we do in other code now.
3. Use the newer NSView.BeginDraggingSession API instead of the deprecated NSView.DragImage. This is needed so that we can provide a DraggingSource object in order to be notified when the drag/drop is over (no matter if successful or not) and call the Finished callback, as expected by Xwt client code.
4. Populate the pasteboard item used for the drag properly, supporting text …
> Fix drag/drop support

- Xwt.XamMac/Xwt.Mac/WindowFrameBackend.cs
- Xwt/Xwt/WindowFrame.cs
This PR fixes some issues in WindowFrameBackend:
* NRE whe transientFor is null (we added to cover this scenario)
* SetTransientFor tries to set the window passed as a parameter in the funcion and in case is not the current one it sets the value.
* Simplifies InternalShow() now takes the parent window and if is Visible and not contains the Window it adds as a children.
> [WindowFrameBackend] Only add parenting when dialog is preparing it be shown

- Xwt.XamMac/Xwt.Mac/TextLayoutBackendHandler.cs
The TextLayoutBackendHandler did not handle NSFont returning null
when trying to get a different weight or size for an NSFont.
System.ArgumentNullException: Value cannot be null. (Parameter
'value')
at ObjCRuntime.ThrowHelper.ThrowArgumentNullException(
String argumentName) in xamarin-macios/src/ObjCRuntime/
ThrowHelper.cs:line 28
at Foundation.NSMutableAttributedString.AddAttribute(
NSString attributeName, NSObject value, NSRange range) in
xamarin-macios/src/build/dotnet/macos/generated-sources/Foundation/
NSMutableAttributedString.g.cs:line 187
at Xwt.Mac.MacTextLayoutBackendHandler.LayoutInfo.
AddAttributeInternal(TextAttribute attribute) in Xwt.XamMac/
Xwt.Mac/TextLayoutBackendHandler.cs:line 210
at Xwt.Mac.MacTextLayoutBackendHandler.LayoutInfo.AddAttribute(
TextAttribute attribute) …
> [Mac] Fix ArgumentNullException when drawing Chinese characters

- Xwt.XamMac/Xwt.Mac/DialogBackend.cs
Fixes scenarios where a dialog is shown but a background window
continues receiving input.
> Mac: Make dialog window key when showing

- Xwt.XamMac/Xwt.Mac/DialogBackend.cs
Use AddChildWindow function introduces a problem with multimonitor when try to move any child window on a different monitor than the parent. I have the feeling that it is a cocoa bug but since it crashes the application, the workaround is to
simply open it with MakeKeyAndOrderFront and/or making it modal. I've done my research and all the apps I've tried use this pattern
> Fixes hang trying to move modal dialog in a secondary monitor

- Xwt.XamMac/Xwt.Mac/DialogBackend.cs
- Xwt.XamMac/Xwt.Mac/WindowBackend.cs
This PR completes https://github.com/mono/xwt/pull/1112 fix, DialogBackend inherits from WindowBackend and this was also usingAdd/RemoveChildWindow, so we cleaned it.
After remove Add/RemoveChildWindow we got into another issue when we were setting ParentWindow property, this is not recommend by Apple and should not be done in modal dialogs, also it broke some system popups like the NSComboBox search in dialogs like scaffolding. I fixed this using a WeakReference cached element.
> [Xwt.Mac] Fixes some parent window issues in cocoa backend

- Xwt.XamMac/Xwt.Mac/AccessibleBackend.cs
The ImageView.Accessible was using the INSAccessibility implementation from the NSImageView when it should have been using the NSImageView's Cell.
Change the AccessibleBackend to use the NSImageView's Cell. The ImageViewBackend puts the NSImageView inside an CustomAlignedContainer so the AccessibleBackend.Initialize method checks for an NSImageView after the CustomAlignedContainer.Child has been found.
> [Mac] Fix ImageView accessibility

- Xwt.XamMac/Xwt.Mac/ImageViewBackend.cs
VSMac is getting some exceptions that we are trying to resurrect the image in this code, so keep a local copy of the NSImage... 
Here is the part of the exception callstack:
"ObjCRuntime.Runtime.MissingCtor(IntPtr,IntPtr,Type,MissingCtorResolution)", "ObjCRuntime.Runtime.ConstructNSObject\[T\](IntPtr,Type,MissingCtorResolution)", 
"ObjCRuntime.Runtime.GetNSObject\[T\](IntPtr)",
"AppKit.NSImageView.get_Image()",
"Xwt.Mac.ImageViewBackend.SetImage(ImageDescription)", "Xwt.ImageView.set_Image(Image)",
> Keep a local ref of the NSImage so it doesn't try to get reconstructed
